"use client";

import { useState } from "react";
import { AlertTriangle, BarChart3, Bot, CheckCircle2, CircleAlert, Cloud, Database, Download, FileUp, Gauge, Mail, MoreHorizontal, RefreshCw, Send, Server, Settings, Users, X } from "lucide-react";
import { useToast } from "@/components/toast/toast-provider";

type Drawer = "storage" | "bandwidth" | "automations" | "cost" | "alerts" | null;

const resources = [
  ["File storage", "684 GB", "1 TB", "316 GB remaining", 68.4, "Normal", "31 Aug 2026"],
  ["Monthly bandwidth", "1.7 TB", "2 TB", "300 GB remaining", 85, "Approaching limit", "31 Jul 2026"],
  ["Email sends", "1,264", "5,000", "3,736 remaining", 25.3, "Normal", "31 Jul 2026"],
  ["SMS sends", "186", "500", "314 remaining", 37.2, "Normal", "31 Jul 2026"],
  ["Automation runs", "3,842", "10,000", "6,158 remaining", 38.4, "Normal", "31 Jul 2026"],
  ["API requests", "48,920", "No configured limit", "Estimated ₱1,120", 0, "No configured limit", "31 Jul 2026"],
  ["Database storage", "5.8 GB", "10 GB", "4.2 GB remaining", 58, "Normal", "31 Aug 2026"],
  ["Backup storage", "18 GB", "50 GB", "32 GB remaining", 36, "Normal", "31 Aug 2026"],
  ["Active user seats", "5", "10 seats", "5 available", 50, "Normal", "31 Jul 2026"],
] as const;

const modules = [
  ["CRM", "4", "126", "2.8 GB", "284", "4,820", "5 minutes ago", "+8%"],
  ["Booking", "5", "68", "620 MB", "412", "8,340", "8 minutes ago", "+12%"],
  ["Projects", "5", "42", "486 GB", "1,126", "11,602", "2 minutes ago", "+18%"],
  ["Files", "5", "2,486", "684 GB", "318", "15,888", "1 minute ago", "+23%"],
  ["POS", "3", "384", "94 MB", "522", "4,362", "14 minutes ago", "+5%"],
  ["Staff Hub", "5", "218", "1.3 GB", "436", "2,104", "22 minutes ago", "+4%"],
  ["Reports", "2", "37", "460 MB", "144", "1,804", "1 hour ago", "+9%"],
];

const alerts = [
  ["Approaching", "Project storage", "Project storage reached 82% of its configured warning threshold.", "25 Jul, 22:10", "684 GB", "835 GB", "Review storage", "New"],
  ["Warning", "Email delivery", "Email delivery failures increased by 18% compared with the previous week.", "25 Jul, 20:46", "24 failed", "20 failed", "Investigate provider", "Investigating"],
  ["Info", "Cost forecast", "Monthly forecast is ₱11,380 against the ₱12,000 budget.", "25 Jul, 18:00", "₱11,380", "₱12,000", "Review budget", "Acknowledged"],
  ["High", "Backup", "One scheduled backup failed and requires review.", "25 Jul, 03:10", "1 failed", "0 failed", "Review backup", "New"],
  ["Normal", "SMS allowance", "314 messages remain in the current allowance.", "24 Jul, 09:00", "186 sent", "500 allowance", "View channel", "Resolved"],
];

const trend = [38, 44, 42, 49, 52, 58, 61, 64, 67, 65, 71, 76];

function Button({ children, primary = false, onClick }: { children: React.ReactNode; primary?: boolean; onClick?: () => void }) { return <button onClick={onClick} className={`inline-flex h-10 items-center justify-center gap-1.5 rounded-control px-3.5 text-sm font-semibold focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--color-kahel-500)] ${primary ? "bg-[var(--color-kahel-500)] text-white hover:bg-[var(--color-kahel-600)]" : "border border-[var(--color-border)] bg-[var(--color-surface)] hover:bg-[var(--color-surface-muted)]"}`}>{children}</button>; }

export default function UsagePage() {
  const { fireToast } = useToast();
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [period, setPeriod] = useState("This month");
  const [metric, setMetric] = useState("Storage growth");
  const [drawer, setDrawer] = useState<Drawer>(null);
  const [exportOpen, setExportOpen] = useState(false);
  const [alertState, setAlertState] = useState(alerts.map((alert) => alert[7]));
  const [fresh, setFresh] = useState("Live data");

  function refresh() { setFresh("Synchronized just now"); fireToast("Usage data refreshed from connected providers.", "success"); }

  return <div className="min-w-0 p-5 pb-14 sm:p-8 lg:p-10">
    <header className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-[var(--color-text-muted)]"><Gauge className="h-3.5 w-3.5 text-[var(--color-kahel-500)]" /> Platform administration</div><h1 className="mt-2 font-display text-[32px] font-semibold tracking-[-0.025em]">Usage</h1><p className="mt-1 text-[15px] text-[var(--color-text-secondary)]">Monitor platform resources, storage, activity and service limits.</p><div className="mt-3 flex flex-wrap items-center gap-2 text-xs text-[var(--color-text-secondary)]"><span className="rounded-pill bg-[var(--color-surface-muted)] px-2.5 py-1 font-semibold">1–31 Jul 2026</span><span>Updated 25 Jul 2026, 10:18 PM GST</span><span className="inline-flex items-center gap-1 rounded-pill bg-[var(--color-success-bg)] px-2 py-1 font-semibold text-[var(--color-success-text)]"><CheckCircle2 className="h-3 w-3" /> {fresh}</span><span className="rounded-pill bg-[var(--color-info-bg)] px-2 py-1 font-semibold text-[var(--color-info-text)]">Studio plan</span></div></div><div className="flex flex-wrap gap-2"><Button onClick={() => setFiltersOpen(!filtersOpen)}><CalendarDaysIcon /> Select billing period</Button><Button onClick={() => setExportOpen(true)}><Download className="h-4 w-4" /> Export usage</Button><Button onClick={() => fireToast("Only Super Admin users can change usage limits.", "info")}><Settings className="h-4 w-4" /> Manage limits</Button><Button primary onClick={refresh}><RefreshCw className="h-4 w-4" /> Refresh data</Button></div></header>
    {filtersOpen && <FilterPanel period={period} setPeriod={setPeriod} onClose={() => setFiltersOpen(false)} />}

    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><Summary icon={<Cloud />} title="Storage used" value="684 GB / 1 TB" detail="68.4% consumed · +42 GB vs. Jun" onClick={() => setDrawer("storage")} /><Summary icon={<FileUp />} title="File transfers" value="2,486 uploads" detail="1.7 TB bandwidth · 7 failed transfers" onClick={() => setDrawer("bandwidth")} /><Summary icon={<Mail />} title="Messages" value="1,264 emails" detail="186 SMS · 31 undelivered" onClick={() => setDrawer("alerts")} /><Summary icon={<Bot />} title="Automations" value="3,842 runs" detail="98.7% successful · 46 hours estimated saved" onClick={() => setDrawer("automations")} /><Summary icon={<Users />} title="Active users" value="5 of 10 seats" detail="2 invited · 0 suspended · 5 available" onClick={() => setDrawer("storage")} /><Summary icon={<BarChart3 />} title="Estimated service cost" value="₱8,460" detail="+₱780 vs. Jun · ₱11,380 forecast" onClick={() => setDrawer("cost")} /></section>

    <section className="mt-8 grid gap-5 2xl:grid-cols-[minmax(0,1.15fr)_minmax(370px,0.85fr)]"><Panel title="Usage trend" subtitle="Provider-reported usage, delayed sources are labelled in the details."><div className="flex flex-wrap gap-2"><Select value={metric} onChange={setMetric} options={["Storage growth", "Bandwidth", "Files uploaded", "Email sends", "SMS sends", "Automation runs", "API requests", "Database activity", "Estimated cost"]} /><div className="flex rounded-control bg-[var(--color-surface-muted)] p-1">{["Daily", "Weekly", "Monthly", "Quarterly"].map((item) => <button key={item} className={`h-8 rounded-[6px] px-2.5 text-xs font-semibold ${item === "Daily" ? "bg-[var(--color-surface)] text-[var(--color-kahel-700)] shadow-sm" : "text-[var(--color-text-secondary)]"}`}>{item}</button>)}</div><Select value="Previous period" onChange={() => undefined} options={["Previous period", "Previous month", "Previous year", "No comparison"]} /></div><div className="mt-5 flex h-48 items-end gap-2" role="img" aria-label={`${metric} trend for July 2026`}><div className="flex h-full w-9 flex-col justify-between text-[10px] text-[var(--color-text-muted)]"><span>100%</span><span>50%</span><span>0%</span></div><div className="flex h-full flex-1 items-end justify-between gap-1.5 border-b border-[var(--color-border)]">{trend.map((height, index) => <button onClick={() => setDrawer("storage")} key={index} className="group flex h-full flex-1 items-end" aria-label={`Day ${index + 1}, ${height}%`}><span className={`w-full rounded-t-sm ${index === trend.length - 1 ? "bg-[var(--color-kahel-500)]" : "bg-[var(--color-ink-300)] group-hover:bg-[var(--color-kahel-400)]"}`} style={{ height: `${height}%` }} /></button>)}</div></div><div className="ml-10 mt-2 flex justify-between text-[10px] text-[var(--color-text-muted)]"><span>1 Jul</span><span>8 Jul</span><span>15 Jul</span><span>22 Jul</span><span>31 Jul</span></div><p className="mt-3 text-xs text-[var(--color-text-secondary)]">{metric} increased 18% from the previous period. Use the chart bars to inspect the underlying usage events.</p></Panel><Panel title="Resource limits" subtitle="Configured limits reset at the stated billing date.">{resources.slice(0, 5).map((resource) => <Resource key={resource[0]} resource={resource} onOpen={() => setDrawer(resource[0] === "File storage" ? "storage" : resource[0] === "Monthly bandwidth" ? "bandwidth" : "alerts")} />)}</Panel></section>

    <section className="mt-8"><SectionTitle title="Usage by module" subtitle="Each measure remains in its source unit; records created are not storage consumption." /><div className="overflow-x-auto rounded-card border border-[var(--color-border)] bg-[var(--color-surface)]"><div className="min-w-[940px]"><div className="grid grid-cols-[1.1fr_.7fr_.9fr_.9fr_.8fr_.9fr_.9fr_.5fr] gap-3 border-b border-[var(--color-border)] bg-[var(--color-canvas)] px-5 py-3 text-[11px] font-semibold uppercase tracking-[0.04em] text-[var(--color-text-secondary)]"><span>Module</span><span>Users</span><span>Records</span><span>Storage</span><span>Automations</span><span>API requests</span><span>Last activity</span><span /></div>{modules.map((item) => <button onClick={() => setDrawer("storage")} key={item[0]} className="grid w-full grid-cols-[1.1fr_.7fr_.9fr_.9fr_.8fr_.9fr_.9fr_.5fr] items-center gap-3 border-b border-[var(--color-border)] px-5 py-3.5 text-left text-sm last:border-0 hover:bg-[var(--color-canvas)]"><span className="font-semibold">{item[0]}</span><span className="tabular-nums">{item[1]}</span><span className="tabular-nums">{item[2]}</span><span className="tabular-nums">{item[3]}</span><span className="tabular-nums">{item[4]}</span><span className="tabular-nums">{item[5]}</span><span className="text-xs text-[var(--color-text-secondary)]">{item[6]}</span><span className="text-xs font-semibold text-[var(--color-success-text)]">{item[7]}</span></button>)}</div></div></section>

    <section className="mt-8 grid gap-5 xl:grid-cols-2"><Panel title="Storage breakdown" subtitle="Provider: Cloudflare R2 · live usage"><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><SmallStat label="Largest category" value="Project photos" detail="298 GB" /><SmallStat label="Largest project" value="KS-2026-0138" detail="42 GB" /><SmallStat label="Files added" value="2,486" detail="This period" /><SmallStat label="Archived" value="74 GB" detail="Recoverable" /></div><div className="mt-5 space-y-3">{[["Project photos", "298 GB", 43], ["Project videos", "241 GB", 35], ["Client deliverables", "72 GB", 10], ["Design files", "23 GB", 3], ["Audio, documents & backups", "50 GB", 7]].map(([name, amount, percent]) => <div key={String(name)}><div className="flex justify-between text-sm"><span className="font-medium">{name}</span><span className="tabular-nums text-[var(--color-text-secondary)]">{amount}</span></div><div className="mt-1.5 h-2 overflow-hidden rounded-pill bg-[var(--color-surface-muted)]"><div className="h-full rounded-pill bg-[var(--color-kahel-500)]" style={{ width: `${percent}%` }} /></div></div>)}</div><button onClick={() => setDrawer("storage")} className="mt-5 text-sm font-semibold text-[var(--color-kahel-700)]">Review storage details</button></Panel><Panel title="Cost and budget" subtitle="Estimated provider costs; confirmed invoices may arrive later."><div className="flex items-end justify-between"><div><div className="font-display text-[30px] font-bold tabular-nums">₱8,460.00</div><div className="mt-1 text-xs text-[var(--color-text-secondary)]">Current-period estimate · ₱7,680 previous period</div></div><span className="rounded-pill bg-[var(--color-success-bg)] px-2.5 py-1 text-xs font-semibold text-[var(--color-success-text)]">Within budget</span></div><div className="mt-5 h-2.5 overflow-hidden rounded-pill bg-[var(--color-surface-muted)]"><div className="h-full w-[70.5%] rounded-pill bg-[var(--color-kahel-500)]" /></div><div className="mt-2 flex justify-between text-xs text-[var(--color-text-secondary)]"><span>₱8,460 estimated</span><span>₱12,000 monthly budget</span></div><div className="mt-5 grid grid-cols-2 gap-3"><SmallStat label="Forecast" value="₱11,380" detail="At period end" /><SmallStat label="Remaining budget" value="₱3,540" detail="29.5% available" /><SmallStat label="Promotional credit" value="₱0.00" detail="No active credit" /><SmallStat label="Confirmed charges" value="₱5,240" detail="Provider billed" /></div><button onClick={() => setDrawer("cost")} className="mt-5 text-sm font-semibold text-[var(--color-kahel-700)]">View provider costs</button></Panel></section>

    <section className="mt-8 grid gap-5 2xl:grid-cols-[minmax(0,1.15fr)_minmax(370px,.85fr)]"><Panel title="Communication usage" subtitle="Only connected channels show activity."><Connection name="Transactional email" status="Connected" details="1,264 sent · 1,209 delivered · 24 failed" cost="Included allowance" icon={<Mail className="h-4 w-4" />} /><Connection name="SMS" status="Connected" details="186 sent · 179 delivered · 7 failed" cost="₱930 estimated" icon={<Send className="h-4 w-4" />} /><Connection name="Instagram messages" status="Not connected" details="No provider data available" cost="Connect channel" icon={<MoreHorizontal className="h-4 w-4" />} /><Connection name="Internal notifications" status="Connected" details="842 delivered · no configured limit" cost="Included" icon={<BellIcon />} /></Panel><Panel title="Automation and integration usage" subtitle="Safe retries are available only for idempotent workflows."><Connection name="Confirmed booking creates a project" status="Active" details="1,126 runs · 100% successful · 0.4s average" cost="Idempotency protected" icon={<Bot className="h-4 w-4" />} /><Connection name="Payment reminder" status="Attention" details="284 runs · 4 retries · 2 failures" cost="Retry review required" icon={<RefreshCw className="h-4 w-4" />} /><Connection name="Supabase" status="Connected" details="48,920 requests · 127 failed · 184ms average" cost="5.8 GB database" icon={<Database className="h-4 w-4" />} /><Connection name="Cloudflare" status="Connected" details="1.7 TB transferred · 7 failed uploads" cost="Storage and bandwidth" icon={<Server className="h-4 w-4" />} /></Panel></section>

    <section className="mt-8"><SectionTitle title="Usage alerts" subtitle="Alert history is preserved after acknowledgement, resolution or dismissal." /><div className="overflow-x-auto rounded-card border border-[var(--color-border)] bg-[var(--color-surface)]"><div className="min-w-[900px]"><div className="grid grid-cols-[.7fr_.9fr_2fr_.9fr_.8fr_.8fr_.7fr] gap-3 border-b border-[var(--color-border)] bg-[var(--color-canvas)] px-5 py-3 text-[11px] font-semibold uppercase tracking-[0.04em] text-[var(--color-text-secondary)]"><span>Severity</span><span>Resource</span><span>Description</span><span>Detected</span><span>Usage</span><span>State</span><span /></div>{alerts.map((alert, index) => <div key={alert[1]} className="grid grid-cols-[.7fr_.9fr_2fr_.9fr_.8fr_.8fr_.7fr] items-center gap-3 border-b border-[var(--color-border)] px-5 py-3.5 text-sm last:border-0"><Severity value={alert[0]} /><span className="font-semibold">{alert[1]}</span><span className="text-[var(--color-text-secondary)]">{alert[2]}</span><span className="text-xs text-[var(--color-text-secondary)]">{alert[3]}</span><span className="text-xs tabular-nums">{alert[4]}</span><span className="text-xs font-semibold">{alertState[index]}</span><button onClick={() => { setAlertState((current) => current.map((state, itemIndex) => itemIndex === index ? "Resolved" : state)); fireToast("Alert marked resolved. History is preserved.", "success"); }} className="text-xs font-semibold text-[var(--color-kahel-700)]">Resolve</button></div>)}</div></div></section>
    <section className="mt-8 rounded-card border border-dashed border-[var(--color-border-strong)] bg-[var(--color-surface)] p-5"><div className="flex items-start gap-3"><Bot className="mt-0.5 h-5 w-5 text-[var(--color-text-muted)]" /><div><h2 className="font-display text-lg font-semibold">AI usage is not configured</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">No AI provider is connected, so no AI requests, tokens, budgets or estimated costs are shown.</p><button onClick={() => fireToast("Open AI provider settings to connect a supported service.", "info")} className="mt-3 text-sm font-semibold text-[var(--color-kahel-700)]">Open integration settings</button></div></div></section>
    {drawer && <UsageDrawer kind={drawer} onClose={() => setDrawer(null)} />}{exportOpen && <ExportDialog onClose={() => setExportOpen(false)} onExport={() => { setExportOpen(false); fireToast("Usage export is preparing. You will be notified when it is ready.", "info"); }} />}
  </div>;
}

function CalendarDaysIcon() { return <span className="text-base leading-none">◷</span>; }
function BellIcon() { return <span className="text-base leading-none">•</span>; }
function Panel({ title, subtitle, children }: { title: string; subtitle: string; children: React.ReactNode }) { return <section className="rounded-card border border-[var(--color-border)] bg-[var(--color-surface)] p-5"><h2 className="font-display text-xl font-semibold">{title}</h2><p className="mt-1 text-xs text-[var(--color-text-secondary)]">{subtitle}</p><div className="mt-5">{children}</div></section>; }
function SectionTitle({ title, subtitle }: { title: string; subtitle: string }) { return <div className="mb-3"><h2 className="font-display text-xl font-semibold">{title}</h2><p className="mt-1 text-xs text-[var(--color-text-secondary)]">{subtitle}</p></div>; }
function Summary({ icon, title, value, detail, onClick }: { icon: React.ReactNode; title: string; value: string; detail: string; onClick: () => void }) { return <button onClick={onClick} className="rounded-card border border-[var(--color-border)] bg-[var(--color-surface)] p-4 text-left hover:border-[var(--color-kahel-500)]"><div className="flex items-center gap-2 text-[var(--color-kahel-700)]">{icon}<span className="text-xs font-semibold uppercase tracking-[0.05em] text-[var(--color-text-secondary)]">{title}</span></div><div className="mt-3 font-display text-[23px] font-bold tabular-nums">{value}</div><p className="mt-1 text-xs text-[var(--color-text-secondary)]">{detail}</p></button>; }
function Resource({ resource, onOpen }: { resource: readonly (string | number)[]; onOpen: () => void }) { const percent = Number(resource[4]); const tone = resource[5] === "Approaching limit" ? "bg-[var(--color-warning)]" : "bg-[var(--color-kahel-500)]"; return <div className="border-b border-[var(--color-border)] py-3.5 last:border-0"><div className="flex items-start justify-between gap-3"><div><div className="text-sm font-semibold">{resource[0]}</div><div className="mt-0.5 text-xs text-[var(--color-text-secondary)]"><span className="font-semibold tabular-nums">{resource[1]}</span> of {resource[2]} · {resource[3]}</div></div><button onClick={onOpen} className="text-xs font-semibold text-[var(--color-kahel-700)]">Details</button></div>{percent > 0 ? <><div className="mt-2 h-2 overflow-hidden rounded-pill bg-[var(--color-surface-muted)]"><div className={`h-full rounded-pill ${tone}`} style={{ width: `${Math.min(percent, 100)}%` }} /></div><div className="mt-1.5 flex justify-between text-[11px] text-[var(--color-text-muted)]"><span>{percent}% · {resource[5]}</span><span>Resets {resource[6]}</span></div></> : <div className="mt-2 text-[11px] text-[var(--color-text-muted)]">{resource[5]} · estimated cost and forecast available</div>}</div>; }
function SmallStat({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-control bg-[var(--color-canvas)] p-3"><div className="text-[10px] font-semibold uppercase tracking-[0.04em] text-[var(--color-text-secondary)]">{label}</div><div className="mt-1 text-sm font-bold tabular-nums">{value}</div><div className="mt-0.5 text-[11px] text-[var(--color-text-muted)]">{detail}</div></div>; }
function Connection({ name, status, details, cost, icon }: { name: string; status: string; details: string; cost: string; icon: React.ReactNode }) { const connected = status === "Connected" || status === "Active"; return <div className="flex items-center gap-3 border-b border-[var(--color-border)] py-3 last:border-0"><span className="text-[var(--color-kahel-700)]">{icon}</span><div className="min-w-0 flex-1"><div className="text-sm font-semibold">{name}</div><div className="mt-0.5 truncate text-xs text-[var(--color-text-secondary)]">{details}</div></div><div className="text-right"><span className={`rounded-pill px-2 py-1 text-[10px] font-semibold ${connected ? "bg-[var(--color-success-bg)] text-[var(--color-success-text)]" : status === "Attention" ? "bg-[var(--color-warning-bg)] text-[var(--color-warning-text)]" : "bg-[var(--color-surface-muted)] text-[var(--color-text-muted)]"}`}>{status}</span><div className="mt-1.5 text-[10px] text-[var(--color-text-muted)]">{cost}</div></div></div>; }
function Severity({ value }: { value: string }) { const cls = value === "High" ? "bg-[var(--color-danger-bg)] text-[var(--color-danger-text)]" : value === "Approaching" || value === "Warning" ? "bg-[var(--color-warning-bg)] text-[var(--color-warning-text)]" : "bg-[var(--color-info-bg)] text-[var(--color-info-text)]"; return <span className={`inline-flex w-fit items-center gap-1 rounded-pill px-2 py-1 text-[10px] font-semibold ${cls}`}>{value === "High" ? <AlertTriangle className="h-3 w-3" /> : <CircleAlert className="h-3 w-3" />}{value}</span>; }
function Select({ value, options, onChange }: { value: string; options: string[]; onChange: (value: string) => void }) { return <select value={value} onChange={(event) => onChange(event.target.value)} className="h-9 rounded-control border border-[var(--color-border)] bg-[var(--color-surface)] px-2.5 text-xs font-semibold">{options.map((item) => <option key={item}>{item}</option>)}</select>; }
function FilterPanel({ period, setPeriod, onClose }: { period: string; setPeriod: (value: string) => void; onClose: () => void }) { return <div className="mt-5 rounded-card border border-[var(--color-border)] bg-[var(--color-surface)] p-4"><div className="grid gap-2 sm:grid-cols-3 xl:grid-cols-6">{[["Date range", period, ["Today", "Last 7 days", "This month", "Last month", "This quarter", "This year", "Custom range"]], ["Usage category", "All categories", ["All categories", "Storage", "Communications", "Automation", "Cost"]], ["Module", "All modules", ["All modules", "Projects", "Files", "Booking", "CRM"]], ["Provider", "All providers", ["All providers", "Cloudflare", "Supabase", "Email provider"]], ["Threshold", "All levels", ["All levels", "Normal", "Approaching", "High usage"]]].map(([label, value, options]) => <label key={String(label)} className="text-[11px] font-semibold text-[var(--color-text-secondary)]">{label}<Select value={String(value)} options={options as string[]} onChange={label === "Date range" ? setPeriod : () => undefined} /></label>)}</div><div className="mt-3 flex justify-end gap-2"><Button onClick={onClose}>Reset filters</Button><Button primary onClick={onClose}>Apply filters</Button></div></div>; }
function UsageDrawer({ kind, onClose }: { kind: Exclude<Drawer, null>; onClose: () => void }) { const info = { storage: ["File storage", "684 GB of 1 TB", "Cloudflare R2", "316 GB remaining", "Largest source: Projects (486 GB)"], bandwidth: ["Monthly bandwidth", "1.7 TB of 2 TB", "Cloudflare", "300 GB remaining", "Transfers increased 18% from the previous period"], automations: ["Automation runs", "3,842 of 10,000", "Kahel workflows", "6,158 remaining", "Confirmed booking project creation is idempotency protected"], cost: ["Estimated service cost", "₱8,460.00", "Connected providers", "₱3,540 budget remaining", "Forecast: ₱11,380.00 at period end"], alerts: ["Usage alerts", "5 alerts this period", "Usage monitoring", "2 new alerts", "No sensitive record contents are exposed here"] }[kind]; return <div className="fixed inset-0 z-50 flex justify-end bg-black/40"><aside className="h-full w-full max-w-md overflow-y-auto bg-[var(--color-surface)] p-5 shadow-[var(--shadow-dialog)]"><div className="flex items-start justify-between"><div><div className="text-xs font-semibold uppercase tracking-[0.08em] text-[var(--color-text-muted)]">Usage details</div><h2 className="mt-1 font-display text-2xl font-semibold">{info[0]}</h2></div><button onClick={onClose} className="rounded-control p-2 hover:bg-[var(--color-surface-muted)]" aria-label="Close usage details"><X className="h-4 w-4" /></button></div><div className="mt-6 grid grid-cols-2 gap-3"><SmallStat label="Current usage" value={info[1]} detail="July billing period" /><SmallStat label="Allowance" value={info[3]} detail="Configured provider limit" /></div><div className="mt-6 rounded-card border border-[var(--color-border)] bg-[var(--color-canvas)] p-4"><div className="font-semibold">Source and forecast</div><p className="mt-2 text-sm text-[var(--color-text-secondary)]">Provider: {info[2]}</p><p className="mt-1 text-sm text-[var(--color-text-secondary)]">{info[4]}</p></div><div className="mt-6"><h3 className="font-display text-lg font-semibold">Recent usage events</h3><div className="mt-3 space-y-3 border-l border-[var(--color-border)] pl-4">{["Usage synchronized from provider", "Threshold check completed", "Usage forecast recalculated"].map((event, index) => <div key={event} className="relative"><span className="absolute -left-[21px] top-1.5 h-2 w-2 rounded-full bg-[var(--color-kahel-500)]" /><div className="text-sm font-medium">{event}</div><div className="text-xs text-[var(--color-text-muted)]">25 Jul 2026 · {10 + index}:18 PM GST</div></div>)}</div></div><button className="mt-7 h-10 w-full rounded-control border border-[var(--color-border)] text-sm font-semibold">Open relevant Settings</button></aside></div>; }
function ExportDialog({ onClose, onExport }: { onClose: () => void; onExport: () => void }) { return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 sm:items-center sm:p-6"><div className="w-full max-w-lg rounded-t-card border border-[var(--color-border)] bg-[var(--color-surface)] p-5 shadow-[var(--shadow-dialog)] sm:rounded-card"><div className="flex items-start justify-between"><div><h2 className="font-display text-xl font-semibold">Export usage</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Exports include the selected period, filters, units, source freshness and permitted data scope.</p></div><button onClick={onClose} className="rounded-control p-2" aria-label="Close export"><X className="h-4 w-4" /></button></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Select value="XLSX" onChange={() => undefined} options={["PDF", "XLSX", "CSV", "Print"]} /><Select value="Usage overview" onChange={() => undefined} options={["Usage overview", "Storage breakdown", "Usage by module", "Cost summary", "Usage alerts"]} /></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" defaultChecked className="accent-[var(--color-kahel-500)]" /> Include active filters and provider notes</label><div className="mt-6 flex justify-end gap-2"><Button onClick={onClose}>Cancel</Button><Button primary onClick={onExport}><Download className="h-4 w-4" /> Prepare export</Button></div></div></div>; }
