"use client";

import { useEffect, useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, Clock3, Mail, RotateCcw, Search, X } from "lucide-react";
import type { MessagesResult } from "@/lib/server/messages-data";
import { canRetryMessage, MESSAGE_STATUSES, sanitizeEmailPreview, type MessageFilters, type TransactionalMessage } from "@/lib/messages";

const dateTime = new Intl.DateTimeFormat("en-PH", { timeZone: "Asia/Manila", dateStyle: "medium", timeStyle: "short" });
const control = "min-h-11 w-full rounded-control border border-[var(--color-border)] bg-[var(--color-surface)] px-3 text-sm";

export function MessagesWorkspace({ result, filters, failedView, canRetry }: { result: MessagesResult; filters: MessageFilters; failedView: boolean; canRetry: boolean }) {
  const [selected, setSelected] = useState<TransactionalMessage | null>(null);
  const [checked, setChecked] = useState<string[]>([]);
  const [confirming, setConfirming] = useState(false);
  const templates = [...new Map(result.templates.map((item) => [item.key, item])).values()];
  const facets = (key: keyof TransactionalMessage) => [...new Set(result.messages.map((item) => String(item[key] ?? "")).filter(Boolean))].sort();
  const eligible = result.messages.filter(canRetryMessage);
  const activeFilters = Object.values(filters).some((value) => value && value !== "all");
  function toggle(id: string) { setChecked((current) => current.includes(id) ? current.filter((item) => item !== id) : current.length < 20 ? [...current, id] : current); }
  return <main className="app-page mx-auto w-full max-w-[1500px] p-4 pb-10 sm:p-6 lg:p-8 xl:p-10">
    <header className="flex flex-wrap items-end justify-between gap-4 border-b border-[var(--color-border)] bg-[var(--color-surface)] pb-9 pt-[34px] px-4 sm:px-6"><div><h1 className="font-display text-[clamp(1.8rem,4vw,2.25rem)] font-semibold leading-11 tracking-[-0.025em]">Transactional emails</h1><p className="mt-1 text-[15px] text-[var(--color-text-secondary)]">Monitor delivery, investigate failures, and review transactional email activity. Times shown in Manila.</p></div>{failedView && canRetry && <button type="button" disabled={!checked.length} onClick={() => setConfirming(true)} className="flex min-h-11 items-center gap-2 rounded-control bg-[var(--color-text-primary)] px-4 text-sm font-semibold text-[var(--color-surface)] disabled:cursor-not-allowed disabled:opacity-40"><RotateCcw className="h-4 w-4" />Retry failed{checked.length ? ` (${checked.length})` : ""}</button>}</header>
    <div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Mail} label="Sent today" value={result.summary.sentToday} /><Metric icon={CheckCircle2} label="Delivered" value={result.summary.delivered} /><Metric icon={Clock3} label="Pending" value={result.summary.pending} /><Metric icon={AlertTriangle} label="Failed" value={result.summary.failed} danger={result.summary.failed > 0} /></div>
    <form method="get" className="mt-5 grid gap-3 rounded-card border border-[var(--color-border)] bg-[var(--color-surface)] p-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6">
      <label className="relative sm:col-span-2"><span className="sr-only">Search messages</span><Search className="pointer-events-none absolute left-3 top-3.5 h-4 w-4 text-[var(--color-text-muted)]" /><input name="search" defaultValue={filters.query} placeholder="Client, recipient, subject, reference, provider ID" className={`${control} pl-9`} /></label>
      {!failedView && <Select name="status" label="Status" value={filters.status} options={MESSAGE_STATUSES.map((item) => [item, item === "all" ? "All statuses" : label(item)])} />}
      <Select name="date" label="Date" value={filters.date} options={[["all", "Any date"], ["today", "Today"], ["7d", "Last 7 days"], ["30d", "Last 30 days"]]} />
      <Select name="template" label="Template" value={filters.template} options={[["", "All templates"], ...templates.map((item) => [item.key, item.name])]} />
      <Select name="module" label="Module" value={filters.module} options={[["", "All modules"], ...facets("module").map((item) => [item, label(item)])]} />
      <Select name="environment" label="Environment" value={filters.environment} options={[["", "All environments"], ...facets("environment").map((item) => [item, label(item)])]} />
      <Select name="trigger" label="Trigger" value={filters.trigger} options={[["", "All triggers"], ...facets("trigger").map((item) => [item, item])]} />
      <Select name="source" label="Source" value={filters.source} options={[["", "All sources"], ...facets("source").map((item) => [item, label(item)])]} />
      <Select name="provider" label="Provider" value={filters.provider} options={[["", "All providers"], ...facets("provider").map((item) => [item, label(item)])]} />
      <Select name="retry" label="Retry eligibility" value={filters.retry} options={[["", "Any retry state"], ["eligible", "Eligible"], ["ineligible", "Not eligible"]]} />
      <label><span className="sr-only">From date</span><input type="date" name="from" defaultValue={filters.from} className={control} /></label><label><span className="sr-only">To date</span><input type="date" name="to" defaultValue={filters.to} className={control} /></label>
      <div className="flex gap-2"><button className="min-h-11 flex-1 rounded-control bg-[var(--color-text-primary)] px-4 text-sm font-semibold text-[var(--color-surface)]">Apply</button>{activeFilters && <a href={failedView ? "/messages/failed" : "/messages/transactional"} className="grid min-h-11 place-items-center rounded-control border border-[var(--color-border)] px-3 text-sm font-semibold">Clear</a>}</div>
    </form>
    {failedView && canRetry && eligible.length > 20 && <p className="mt-3 text-xs text-[var(--color-text-muted)]">Select up to 20 eligible transient failures per retry batch.</p>}
    {result.reason && <div className="mt-4 rounded-control border border-[var(--color-warning-border)] bg-[var(--color-warning-bg)] px-4 py-3 text-sm text-[var(--color-warning-text)]">{result.reason}</div>}
    {!result.messages.length ? <Empty available={result.available} filtered={activeFilters} failed={failedView} /> : <MessageList messages={result.messages} failedView={failedView} canRetry={canRetry} checked={checked} toggle={toggle} onSelect={setSelected} />}
    {selected && <MessageDrawer message={selected} onClose={() => setSelected(null)} />}
    {confirming && <RetryDialog messages={result.messages.filter((item) => checked.includes(item.id))} onClose={() => setConfirming(false)} onComplete={() => { setChecked([]); setConfirming(false); window.location.reload(); }} />}
  </main>;
}

function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (char) => char.toUpperCase()); }
function Select({ name, label: ariaLabel, value, options }: { name: string; label: string; value: string; options: string[][] }) { return <label><span className="sr-only">{ariaLabel}</span><select name={name} defaultValue={value} className={control}>{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></label>; }
function Metric({ icon: Icon, label: text, value, danger }: { icon: typeof Mail; label: string; value: number; danger?: boolean }) { return <div className="rounded-card border border-[var(--color-border)] bg-[var(--color-surface)] p-4"><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.06em] text-[var(--color-text-muted)]"><Icon className={`h-4 w-4 ${danger ? "text-[var(--color-danger-text)]" : "text-[var(--color-kahel-600)]"}`} />{text}</div><p className="mt-3 font-display text-2xl font-semibold">{value.toLocaleString()}</p></div>; }
function Empty({ available, filtered, failed }: { available: boolean; filtered: boolean; failed: boolean }) { return <section className="mt-5 grid min-h-64 place-items-center rounded-card border border-dashed border-[var(--color-border-strong)] bg-[var(--color-surface)] p-8 text-center"><div><Mail className="mx-auto h-6 w-6 text-[var(--color-text-muted)]" /><h2 className="mt-3 font-display text-lg font-semibold">{!available ? "Message source unavailable" : filtered ? "No matching messages" : failed ? "No failed deliveries" : "No transactional emails"}</h2><p className="mx-auto mt-2 max-w-md text-sm text-[var(--color-text-secondary)]">{!available ? "Canonical transactional message data is unavailable." : filtered ? "Change or clear the URL filters to broaden the results." : "New delivery records will appear here automatically."}</p></div></section>; }

function MessageList({ messages, failedView, canRetry, checked, toggle, onSelect }: { messages: TransactionalMessage[]; failedView: boolean; canRetry: boolean; checked: string[]; toggle: (id: string) => void; onSelect: (message: TransactionalMessage) => void }) {
  const columns = failedView && canRetry ? "lg:grid-cols-[44px_minmax(220px,1.2fr)_minmax(180px,1fr)_150px_130px_150px]" : "lg:grid-cols-[minmax(220px,1.2fr)_minmax(180px,1fr)_150px_130px_150px]";
  return <section className="mt-5 overflow-hidden rounded-card border border-[var(--color-border)] bg-[var(--color-surface)]"><div className={`hidden ${columns} gap-4 border-b border-[var(--color-border)] px-4 py-3 text-xs font-semibold uppercase tracking-[.06em] text-[var(--color-text-muted)] lg:grid`}>{failedView && canRetry && <span>Select</span>}<span>Subject</span><span>Client / recipient</span><span>Template / module</span><span>Status</span><span>Updated</span></div>{messages.map((message) => { const eligible = canRetryMessage(message); return <article key={message.id} className={`border-b border-[var(--color-border)] p-4 last:border-0 lg:grid ${columns} lg:items-center lg:gap-4`}>
    {failedView && canRetry && <label className="mb-3 flex min-h-11 items-center gap-2 lg:mb-0" title={eligible ? "Select for retry" : "Only transient failed messages are retryable"}><input type="checkbox" checked={checked.includes(message.id)} disabled={!eligible || (!checked.includes(message.id) && checked.length >= 20)} onChange={() => toggle(message.id)} className="h-5 w-5 accent-[var(--color-kahel-600)]" /><span className="text-xs lg:sr-only">Select for retry</span></label>}
    <button type="button" onClick={() => onSelect(message)} className="min-h-11 min-w-0 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[var(--color-kahel-500)]"><span className="block truncate text-sm font-semibold">{message.subject}</span><span className="mt-1 block truncate text-xs text-[var(--color-text-muted)]">{message.id}</span></button>
    <div className="mt-2 min-w-0 lg:mt-0"><span className="block truncate text-sm">{message.clientName ?? message.recipientName ?? "No client name"}</span><span className="block truncate text-xs text-[var(--color-text-muted)]">{message.recipient}</span></div>
    <div className="mt-2 text-xs lg:mt-0"><span className="block truncate font-semibold">{message.templateKey}{message.templateVersion ? ` v${message.templateVersion}` : ""}</span><span className="text-[var(--color-text-muted)]">{label(message.module)}</span></div>
    <div className="mt-3 lg:mt-0"><Status value={message.status} /></div><span className="mt-2 block text-xs text-[var(--color-text-muted)] lg:mt-0">{formatDate(message.updatedAt)}</span>
  </article>; })}</section>;
}

function Status({ value }: { value: string }) { const failed = ["failed", "bounced", "complained", "suppressed"].includes(value); const delivered = value === "delivered"; return <span className={`inline-block rounded-pill px-2.5 py-1 text-xs font-semibold ${failed ? "bg-[var(--color-danger-bg)] text-[var(--color-danger-text)]" : delivered ? "bg-[var(--color-success-bg)] text-[var(--color-success-text)]" : "bg-[var(--color-info-bg)] text-[var(--color-info-text)]"}`}>{label(value)}</span>; }
function formatDate(value: string | null) { return value ? dateTime.format(new Date(value)) : "Not recorded"; }

function MessageDrawer({ message, onClose }: { message: TransactionalMessage; onClose: () => void }) {
  const closeRef = useRef<HTMLButtonElement>(null), panelRef = useRef<HTMLElement>(null);
  const previewUnavailable = message.containsSecureContent || message.contentRedacted || (!message.htmlBody && !message.textBody);
  const [preview, setPreview] = useState<"html" | "text">(!previewUnavailable && message.htmlBody ? "html" : "text");
  useDialog(panelRef, closeRef, onClose);
  const references: [string, string | null][] = [["Booking", message.bookingReference], ["Invoice", message.invoiceReference], ["Payment", message.paymentReference ?? message.paymentId], ["Project", message.projectReference], ["Gallery", message.galleryReference]];
  return <div className="fixed inset-0 z-50 flex justify-end bg-black/40" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section ref={panelRef} role="dialog" aria-modal="true" aria-labelledby="message-detail-title" className="h-dvh w-full overflow-y-auto bg-[var(--color-surface)] shadow-[var(--shadow-dialog)] sm:max-w-2xl"><header className="sticky top-0 z-10 flex items-start gap-3 border-b border-[var(--color-border)] bg-[var(--color-surface)] p-4 sm:p-5"><div className="min-w-0 flex-1"><p className="text-xs text-[var(--color-text-muted)]">{message.templateKey}{message.templateVersion ? ` · Version ${message.templateVersion}` : ""}</p><h2 id="message-detail-title" className="mt-1 font-display text-xl font-semibold">{message.subject}</h2></div><button ref={closeRef} type="button" onClick={onClose} className="grid min-h-11 min-w-11 place-items-center rounded-control hover:bg-[var(--color-surface-muted)]" aria-label="Close message detail"><X className="h-5 w-5" /></button></header><div className="space-y-6 p-4 sm:p-5">
    <dl className="grid gap-3 rounded-card bg-[var(--color-canvas)] p-4 sm:grid-cols-2"><Detail label="Client" value={message.clientName} /><Detail label="Recipient" value={`${message.recipientName ? `${message.recipientName} · ` : ""}${message.recipient}`} /><Detail label="Status" value={label(message.status)} /><Detail label="Provider" value={label(message.provider)} /><Detail label="Provider ID" value={message.providerMessageId} /><Detail label="Environment" value={label(message.environment)} /><Detail label="Trigger" value={message.trigger} /><Detail label="Source" value={`${label(message.source)}${message.sourceReference ? ` · ${message.sourceReference}` : ""}`} /><Detail label="Actor" value={message.actor} /><Detail label="Attempts" value={`${message.attemptCount} of ${message.maxAttempts}`} />{references.map(([key, value]) => value && <Detail key={key} label={key} value={value} />)}<Detail label="Message ID" value={message.id} /></dl>
    <section><h3 className="font-display font-semibold">Timestamps</h3><dl className="mt-3 grid gap-3 sm:grid-cols-2"><Detail label="Created" value={formatDate(message.createdAt)} /><Detail label="Queued" value={formatDate(message.queuedAt)} /><Detail label="Accepted" value={formatDate(message.acceptedAt)} /><Detail label="Sent" value={formatDate(message.sentAt)} /><Detail label="Delivered" value={formatDate(message.deliveredAt)} /><Detail label="Failed" value={formatDate(message.failedAt)} /><Detail label="Cancelled" value={formatDate(message.cancelledAt)} /><Detail label="Latest update" value={formatDate(message.updatedAt)} /><Detail label="Next attempt" value={formatDate(message.nextAttemptAt)} /></dl></section>
    {(message.lastError || message.lastErrorCode) && <section className="rounded-control border border-[var(--color-danger-border)] bg-[var(--color-danger-bg)] p-4"><h3 className="text-sm font-semibold text-[var(--color-danger-text)]">Safe failure detail</h3><p className="mt-1 break-words text-sm text-[var(--color-danger-text)]">{message.lastErrorCode && `${message.lastErrorCode}: `}{message.lastError}</p></section>}
    <section><div className="flex items-center justify-between gap-3"><h3 className="font-display font-semibold">Content preview</h3>{!previewUnavailable && <div className="flex rounded-control border border-[var(--color-border)] p-0.5">{message.htmlBody && <PreviewButton active={preview === "html"} onClick={() => setPreview("html")}>HTML</PreviewButton>}{message.textBody && <PreviewButton active={preview === "text"} onClick={() => setPreview("text")}>Text</PreviewButton>}</div>}</div>{previewUnavailable ? <p className="mt-3 rounded-control bg-[var(--color-canvas)] p-4 text-sm text-[var(--color-text-secondary)]">Preview unavailable for secure or redacted content.</p> : preview === "html" && message.htmlBody ? <iframe title="Sanitized email preview" sandbox="" srcDoc={sanitizeEmailPreview(message.htmlBody)} className="mt-3 h-80 w-full rounded-control border border-[var(--color-border)] bg-white" /> : <pre className="mt-3 max-h-80 overflow-auto whitespace-pre-wrap rounded-control border border-[var(--color-border)] bg-[var(--color-canvas)] p-4 text-xs">{message.textBody}</pre>}</section>
    <Timeline message={message} />
    <History title="Resend history" empty="No resends are recorded." rows={message.resendHistory.map((item) => ({ id: item.id, title: `Resend ${item.sequence} · ${label(item.status)}`, date: item.createdAt, detail: [item.actor, item.reason].filter(Boolean).join(" · ") }))} />
    <History title="Audit" empty="No related audit entries are available." rows={message.audit.map((item) => ({ id: item.id, title: item.event, date: item.occurredAt, detail: [item.actor, item.detail].filter(Boolean).join(" · ") }))} />
  </div></section></div>;
}

function useDialog(panelRef: React.RefObject<HTMLElement | null>, closeRef: React.RefObject<HTMLButtonElement | null>, onClose: () => void) { useEffect(() => { const returnFocus = document.activeElement as HTMLElement | null; const previous = document.body.style.overflow; document.body.style.overflow = "hidden"; closeRef.current?.focus(); function keydown(event: KeyboardEvent) { if (event.key === "Escape") onClose(); if (event.key !== "Tab" || !panelRef.current) return; const focusable = [...panelRef.current.querySelectorAll<HTMLElement>('button,[href],input,select,textarea,[tabindex]:not([tabindex="-1"])')].filter((item) => !item.hasAttribute("disabled")); const first = focusable[0], last = focusable.at(-1); if (!first || !last) return; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } document.addEventListener("keydown", keydown); return () => { document.body.style.overflow = previous; document.removeEventListener("keydown", keydown); returnFocus?.focus(); }; }, [closeRef, onClose, panelRef]); }
function PreviewButton({ active, onClick, children }: { active: boolean; onClick: () => void; children: React.ReactNode }) { return <button type="button" onClick={onClick} className={`min-h-11 rounded-[6px] px-3 text-xs font-semibold ${active ? "bg-[var(--color-text-primary)] text-[var(--color-surface)]" : ""}`}>{children}</button>; }
function Detail({ label: text, value }: { label: string; value: string | null }) { return <div><dt className="text-xs font-semibold text-[var(--color-text-muted)]">{text}</dt><dd className="mt-1 break-all text-sm">{value ?? "Not recorded"}</dd></div>; }
function Timeline({ message }: { message: TransactionalMessage }) { const rows = [...message.attempts.map((item) => ({ id: `a-${item.id}`, title: `Attempt ${item.number ?? ""}: ${label(item.status)}`, date: item.finishedAt ?? item.attemptedAt, detail: [item.actor, item.providerMessageId, item.errorCode, item.error].filter(Boolean).join(" · ") })), ...message.events.map((item) => ({ id: `e-${item.id}`, title: `${label(item.type)}${item.status ? ` · ${label(item.status)}` : ""}`, date: item.occurredAt, detail: [item.providerMessageId, item.detail].filter(Boolean).join(" · ") }))].sort((a, b) => b.date.localeCompare(a.date)); return <History title="Status timeline" empty="No attempt or provider event records are available." rows={rows} />; }
function History({ title, empty, rows }: { title: string; empty: string; rows: { id: string; title: string; date: string; detail: string }[] }) { return <section><h3 className="font-display font-semibold">{title}</h3>{rows.length ? <ol className="mt-3 space-y-3 border-l border-[var(--color-border)] pl-4">{rows.map((row) => <li key={row.id}><p className="text-sm font-semibold">{row.title}</p><p className="mt-0.5 text-xs text-[var(--color-text-muted)]">{formatDate(row.date)}</p>{row.detail && <p className="mt-1 break-words text-xs text-[var(--color-text-secondary)]">{row.detail}</p>}</li>)}</ol> : <p className="mt-2 text-sm text-[var(--color-text-secondary)]">{empty}</p>}</section>; }

function RetryDialog({ messages, onClose, onComplete }: { messages: TransactionalMessage[]; onClose: () => void; onComplete: () => void }) {
  const [reason, setReason] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); if (reason.trim().length < 5 || messages.length > 20) return; setBusy(true); setError(""); const batchKey = crypto.randomUUID(); for (const message of messages) { try { const response = await fetch(`/api/email/messages/${message.id}/resend`, { method: "POST", headers: { "Content-Type": "application/json", "Idempotency-Key": `${batchKey}:${message.id}` }, body: JSON.stringify({ reason: reason.trim() }) }); if (!response.ok) { const body = await response.json().catch(() => null) as { error?: string } | null; setError(`Stopped after a safe failure: ${body?.error ?? "Retry was not accepted."}`); setBusy(false); return; } } catch { setError("Stopped because the connection was interrupted. Completed requests remain idempotent."); setBusy(false); return; } } onComplete(); }
  return <div className="fixed inset-0 z-[60] flex items-end justify-center bg-black/40 sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-labelledby="retry-title" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><form onSubmit={submit} className="w-full max-w-lg rounded-t-modal bg-[var(--color-surface)] p-5 shadow-[var(--shadow-dialog)] sm:rounded-modal"><div className="flex items-start gap-4"><div><h2 id="retry-title" className="font-display text-xl font-semibold">Retry failed emails</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">Retry {messages.length} eligible transient {messages.length === 1 ? "failure" : "failures"}, one at a time. Processing stops safely on the first error.</p></div><button type="button" disabled={busy} onClick={onClose} className="ml-auto grid min-h-11 min-w-11 place-items-center rounded-control" aria-label="Close retry dialog"><X className="h-5 w-5" /></button></div><label className="mt-5 block text-sm font-semibold">Reason<textarea autoFocus required minLength={5} maxLength={180} value={reason} onChange={(event) => setReason(event.target.value)} rows={3} placeholder="Why should these messages be retried?" className="mt-2 w-full rounded-control border border-[var(--color-border)] p-3 font-normal" /></label>{error && <p role="alert" className="mt-3 text-sm text-[var(--color-danger-text)]">{error}</p>}<div className="mt-5 flex justify-end gap-2"><button type="button" disabled={busy} onClick={onClose} className="min-h-11 rounded-control border border-[var(--color-border)] px-4 text-sm font-semibold">Cancel</button><button disabled={busy || reason.trim().length < 5 || !messages.length || messages.length > 20} className="min-h-11 rounded-control bg-[var(--color-text-primary)] px-4 text-sm font-semibold text-[var(--color-surface)] disabled:opacity-40">{busy ? "Retrying..." : "Confirm retry"}</button></div></form></div>;
}
