export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Table<Row extends Record<string, unknown>> = { Row: Row; Insert: Partial<Row>; Update: Partial<Row>; Relationships: [] };

type ClientRow = { id: string; name: string; status: string; account_type: string; external_ref: string; primary_contact_profile_id: string | null; created_at: string; updated_at: string };
type ProfileRow = { id: string; client_id: string; user_id: string | null; email: string; normalized_email: string; normalized_mobile: string | null; first_name: string; last_name: string; mobile: string | null; status: string; email_verified_at: string | null; created_at: string; updated_at: string };
type BookingRow = { id: string; client_id: string; client_profile_id: string; idempotency_key: string; request_fingerprint: string; reference: string; service_type: string; service_id: string; service_date: string; service_time: string; starts_at: string; ends_at: string; timezone: string; resource_id: string; duration_minutes_snapshot: number; prep_buffer_minutes_snapshot: number; cleanup_buffer_minutes_snapshot: number; reservation_hold_id: string | null; reservation_owner_token_hash: string | null; cancellation_reason: string | null; cancellation_actor_id: string | null; cancelled_at: string | null; location: string; payment_type: string; currency: string; subtotal_amount_php: number; total_amount_php: number; paid_amount_php: number; refunded_amount_php: number; status: string; payment_status: string; completed_at: string | null; attendance: string; kind: string; duplicate_of: string | null; linked_booking_id: string | null; loyalty_exclusion_reason: string | null; loyalty_excluded_by: string | null; loyalty_excluded_at: string | null; reward_id: string | null; paymongo_checkout_session_id: string | null; paymongo_checkout_url: string | null; paymongo_payment_id: string | null; paymongo_payment_intent_id: string | null; paymongo_payment_method: string | null; paymongo_payment_description: string | null; paymongo_paid_at: string | null; paymongo_available_at: string | null; paymongo_credited_at: string | null; paymongo_checkout_expires_at: string | null; checkout_creation_started_at: string | null; created_at: string; updated_at: string };
type ProjectRow = { id: string; client_id: string; booking_id: string | null; reference: string; title: string; description: string | null; status: string; starts_at: string | null; completed_at: string | null; created_at: string; updated_at: string };
type InvoiceRow = { id: string; client_id: string; project_id: string | null; booking_id: string | null; reference: string; currency: string; subtotal_amount_php: number; tax_amount_php: number; total_amount_php: number; paid_amount_php: number; refunded_amount_centavos: number; status: string; issued_at: string | null; due_at: string | null; paid_at: string | null; created_at: string; updated_at: string };
type PaymentRow = { id: string; client_id: string; booking_id: string; processor: string; source: string; payment_method: string; payment_purpose: string; status: string; settlement_status: string; currency: string; balance_component_centavos: number; add_on_amount_centavos: number; amount_centavos: number; refunded_amount_centavos: number; idempotency_key: string; request_fingerprint: string; note: string | null; receipt_requested: boolean; create_invoice_requested: boolean; provider_checkout_session_id: string | null; provider_payment_id: string | null; provider_payment_intent_id: string | null; checkout_url: string | null; checkout_expires_at: string | null; payment_method_detail: string | null; provider_description: string | null; prepared_by: string | null; paid_at: string | null; failed_at: string | null; cancelled_at: string | null; expired_at: string | null; posted_at: string | null; created_at: string; updated_at: string };
type PaymentLineItemRow = { id: string; payment_id: string; client_id: string; line_type: string; product_id: string | null; description: string; quantity: number; unit_price_centavos: number; total_centavos: number; created_at: string };
type PaymentAllocationRow = { id: string; payment_id: string; client_id: string; booking_id: string; invoice_id: string | null; amount_centavos: number; created_at: string };
type InvoiceItemRow = { id: string; invoice_id: string; client_id: string; product_id: string | null; payment_line_item_id: string | null; kind: string; description: string; quantity: number; unit_price_centavos: number; total_centavos: number; created_at: string };
type CashTransactionRow = { id: string; payment_id: string; client_id: string; register_session_id: string | null; amount_centavos: number; cash_received_centavos: number; change_centavos: number; note: string | null; occurred_at: string; recorded_by: string; created_at: string };
type ReceiptRow = { id: string; payment_id: string; client_id: string; booking_id: string; invoice_id: string | null; receipt_number: string; client_name: string; booking_reference: string; invoice_reference: string | null; payment_method: string; amount_centavos: number; cash_received_centavos: number | null; change_centavos: number | null; note: string | null; issued_at: string; created_at: string };
type ReceiptLineItemRow = { id: string; receipt_id: string; client_id: string; description: string; quantity: number; unit_price_centavos: number; total_centavos: number; created_at: string };
type PaymentEventRow = { id: string; payment_id: string; provider: string; provider_event_id: string | null; event_type: string; event_status: string; occurred_at: string; received_at: string; processed_at: string | null; payload: Json; processing_error: string | null };
type PaymentSettlementRow = { id: string; payment_id: string; provider: string; provider_settlement_id: string | null; status: string; gross_amount_centavos: number; fee_amount_centavos: number | null; net_amount_centavos: number | null; available_at: string | null; settled_at: string | null; created_at: string; updated_at: string };
type InventoryMovementRow = { id: string; product_id: string; payment_line_item_id: string; quantity_delta: number; stock_after: number; unit_price_centavos: number; reason: string; created_at: string };
type LocationRow = { id: string; code: string; name: string; minimum_cash_centavos: number; active: boolean; created_at: string };
type CashRegisterRow = { id: string; location_id: string; code: string; name: string; active: boolean; created_at: string };
type CashRegisterSessionRow = { id: string; register_id: string; status: string; opening_amount_centavos: number; expected_amount_centavos: number | null; counted_amount_centavos: number | null; variance_centavos: number | null; opened_by: string; opened_at: string; opening_note: string | null; close_submitted_at: string | null; close_note: string | null; reviewed_by: string | null; reviewed_at: string | null; review_note: string | null; closed_at: string | null; created_at: string };
type CashRegisterSessionEventRow = { id: string; register_session_id: string; event_type: string; actor_id: string; note: string | null; expected_amount_centavos: number | null; counted_amount_centavos: number | null; variance_centavos: number | null; occurred_at: string; created_at: string };
type CashRegisterEventRow = { id: string; register_session_id: string; event_type: string; direction: string; amount_centavos: number; payment_id: string | null; refund_id: string | null; idempotency_key: string | null; reason: string | null; actor_id: string; occurred_at: string; created_at: string };
type PaymentRefundRow = { id: string; approval_request_id: string; payment_id: string; booking_id: string; client_id: string; amount_centavos: number; refund_method: string; reason: string; idempotency_key: string; actor_id: string; refunded_at: string; register_session_id: string | null; created_at: string };
type GalleryRow = { id: string; client_id: string; project_id: string; booking_id: string | null; slug: string; title: string; description: string | null; status: string; access_rule: string; published: boolean; published_at: string | null; downloads_enabled: boolean; favorites_enabled: boolean; selections_enabled: boolean; watermark_enabled: boolean; expires_at: string | null; session_date: string | null; cover_media_asset_id: string | null; created_by: string | null; created_at: string; updated_at: string };
type GalleryAssetRow = { id: string; gallery_id: string; client_id: string; media_asset_id: string | null; storage_path: string; asset_type: string; title: string | null; alt_text: string | null; caption: string | null; sort_order: number; width: number | null; height: number | null; visibility: string; approval_status: string; downloadable: boolean; download_variant: string; created_at: string; updated_at: string };
type MediaAssetRow = { id: string; client_id: string | null; project_id: string | null; private_r2_key: string | null; public_r2_key: string | null; cloudflare_image_id: string | null; original_filename: string; original_extension: string | null; mime_type: string; byte_size: number | null; width: number | null; height: number | null; aspect_ratio: number | null; focal_x: number | null; focal_y: number | null; checksum_sha256: string | null; alt_text: string | null; decorative: boolean; caption: string | null; usage_type: string; visibility: string; status: string; processing_failure_code: string | null; processing_failure_message: string | null; source_asset_id: string | null; created_by: string | null; updated_by: string | null; uploaded_at: string | null; processed_at: string | null; dominant_color: string | null; created_at: string; updated_at: string };
type GalleryFavoriteRow = { gallery_id: string; gallery_asset_id: string; client_id: string; client_profile_id: string; created_at: string };
type GallerySelectionRow = { gallery_id: string; gallery_asset_id: string; client_id: string; client_profile_id: string; submission_status: string; note: string | null; submitted_at: string | null; created_at: string; updated_at: string };
type GalleryActivityRow = { id: number; gallery_id: string; client_id: string; client_profile_id: string | null; actor_user_id: string | null; event_type: string; gallery_asset_id: string | null; metadata: Json; created_at: string };
type MediaUploadSessionRow = { id: string; client_id: string | null; project_id: string | null; created_by: string | null; upload_token_hash: string; expected_mime_type: string | null; expected_byte_size: number | null; private_r2_key: string; status: string; expires_at: string; completed_asset_id: string | null; failure_message: string | null; created_at: string; updated_at: string };
type MediaProcessingJobRow = { id: string; media_asset_id: string; client_id: string | null; job_type: string; idempotency_key: string; status: string; attempts: number; available_at: string; locked_at: string | null; locked_by: string | null; finished_at: string | null; last_error: string | null; input: Json; output: Json | null; created_at: string; updated_at: string };
type GalleryDownloadArchiveRow = { id: string; gallery_id: string; client_id: string; requested_by_profile_id: string | null; idempotency_key: string; status: string; private_r2_key: string | null; byte_size: number | null; expires_at: string | null; failure_message: string | null; created_at: string; updated_at: string };
type GalleryEmailOutboxRow = { id: string; gallery_id: string; client_id: string; recipient_profile_id: string; template_key: string; idempotency_key: string; payload: Json; status: string; attempts: number; available_at: string; processing_at: string | null; sent_at: string | null; provider_message_id: string | null; last_error: string | null; created_at: string; updated_at: string };
type MessageRow = { id: string; client_id: string; sender_profile_id: string | null; project_id: string | null; sender: string; body: string; read_at: string | null; created_at: string };
type AuditRow = { id: string; client_id: string | null; client_profile_id: string | null; actor_user_id: string | null; actor_type: string; action: string; entity_type: string; entity_id: string | null; request_id: string | null; ip_address: string | null; user_agent: string | null; metadata: Json; created_at: string };
type ResolutionRow = { id: string; auth_user_id: string | null; normalized_email: string; candidate_profile_ids: string[]; reason: string; status: string; resolution: Json | null; resolved_by: string | null; resolved_at: string | null; created_at: string; updated_at: string };
type RateLimitRow = { scope: string; key_hash: string; window_started_at: string; attempts: number; expires_at: string; updated_at: string };
type StaffProfileRow = { user_id: string; role: string; display_name: string; active: boolean; can_manage_bookings: boolean; can_manage_loyalty: boolean; can_manage_rewards: boolean; can_manage_galleries: boolean; created_at: string; updated_at: string };
type StaffEmergencyContactRow = { id: string; staff_id: string; name: string; relationship: string; phone: string; email: string | null; created_at: string };
type StaffRecoveryEmailRow = { staff_id: string; recovery_email: string | null; pending_email: string | null; verification_code_hash: string | null; verification_expires_at: string | null; created_at: string; updated_at: string };
type ServiceRow = { id: string; code: string; name: string; active: boolean; duration_minutes: number; prep_buffer_minutes: number; cleanup_buffer_minutes: number; minimum_notice_minutes: number; maximum_advance_days: number; default_resource_id: string; created_at: string; updated_at: string };
type BookingResourceRow = { id: string; code: string; name: string; type: string; timezone: string; capacity: number; active: boolean; hold_minutes: number; created_at: string; updated_at: string };
type BookingReservationRow = { id: string; booking_id: string | null; service_id: string; resource_id: string; starts_at: string; ends_at: string; blocked_starts_at: string; blocked_ends_at: string; blocked_range: string; type: string; status: string; expires_at: string | null; idempotency_key: string | null; request_fingerprint: string | null; owner_token_hash: string | null; created_at: string; updated_at: string; released_at: string | null };
type LoyaltyProgramRow = { id: string; code: string; name: string; launch_date: string; active: boolean; threshold: number; reward_service_id: string; expires_after: string | null; retroactive: boolean; created_at: string; updated_at: string };
type LoyaltyRewardRow = { id: string; client_id: string; program_id: string; sequence: number; threshold: number; service_id: string; status: string; issued_at: string; reserved_at: string | null; redeemed_at: string | null; voided_at: string | null; expires_at: string | null; review_required: boolean; review_reason: string | null; updated_at: string };
type LoyaltyEligibilityRow = { booking_id: string; program_id: string; client_id: string; state: string; contribution: number; reason_code: string; evaluated_at: string };
type LoyaltyEventRow = { id: number; booking_id: string | null; program_id: string; client_id: string; event_key: string; event_type: string; delta: number; reason_code: string; created_at: string };
type LoyaltyOutboxRow = { id: string; reward_id: string; client_id: string; template_key: string; payload: Json; status: string; attempts: number; available_at: string; processing_at: string | null; sent_at: string | null; provider_message_id: string | null; last_error: string | null; created_at: string; updated_at: string };
type LoyaltyTermsRow = { id: string; program_id: string; version: number; effective_at: string; body: string; published_at: string | null; created_at: string };
type LoyaltyAuditRow = { id: number; actor_user_id: string | null; action: string; entity_type: string; entity_id: string; reason: string; previous_data: Json; new_data: Json; created_at: string };
type ProductRow = { id: string; sku: string; name: string; category: string; price: number; stock: number; swatch: string; active: boolean; created_at: string; updated_at: string };
type PosSaleRow = { id: string; reference: string; client_id: string | null; method: string; subtotal: number; total: number; currency: string; recorded_at: string; recorded_by: string | null };
type PosSaleItemRow = { id: string; sale_id: string; product_id: string | null; description: string; unit_price: number; quantity: number; total_price: number };
type PosCatalogRow = { id: string; catalog_key: string; title: string; subtitle: string | null; unit_label: string | null; active: boolean; created_at: string };
type PosCatalogItemRow = { id: string; catalog_id: string; code: string; name: string; detail: string | null; price: number; quantity_info: string | null; sort_order: number; active: boolean };
type EquipmentRow = { id: string; id_tag: string; serial: string; name: string; category: string; status: string; note: string | null; location: string | null; created_at: string; updated_at: string };
type EquipmentCheckoutRow = { id: string; equipment_id: string; checked_out_by: string | null; purpose: string; checked_out_at: string; expected_return_at: string | null; returned_at: string | null; condition_on_return: string | null };
type MaintenanceRow = { id: string; task: string; asset_label: string; maintenance_type: string; issue: string | null; assignee: string; next_due: string | null; recurrence: string | null; estimated_cost: number | null; warranty: string | null; status: string; created_at: string; updated_at: string };
type MarketingCampaignRow = { id: string; name: string; channel: string; spend: number; bookings_attributed: number; status: string; starts_at: string | null; ends_at: string | null; created_at: string; created_by: string | null };
type QuotationRow = { id: string; reference: string; client_id: string | null; service_type: string; total: number; status: string; valid_until: string | null; notes: string | null; created_at: string; updated_at: string; created_by: string | null };
type GlitchRow = { id: string; reference: string; title: string; description: string; category: string; severity: string; status: string; location_or_system: string | null; operations_blocked: boolean; workaround: string | null; resolution_summary: string | null; reporter_name: string | null; reported_by: string | null; assigned_to: string | null; resolved_by: string | null; booking_id: string | null; project_id: string | null; client_id: string | null; linked_task_id: string | null; observed_at: string; resolved_at: string | null; closed_at: string | null; archived_at: string | null; created_at: string; updated_at: string };
type GlitchActivityRow = { id: number; glitch_id: string; actor_id: string | null; event_type: string; message: string; metadata: Json; created_at: string };
type GlitchAttachmentRow = { id: string; glitch_id: string; storage_path: string; filename: string; content_type: string; byte_size: number; uploaded_by: string | null; created_at: string };
type FeedbackReportRow = { id: string; iid: string; title: string; summary: string | null; app: string; kind: string; status: string; priority: string; submitted_at: string; submitted_by: string | null; checked: boolean };
type TaskRow = { id: string; title: string; description: string | null; column_status: string; priority: string; category: string; assignee: string | null; due_date: string | null; recurrence: string | null; linked_ref: string | null; sort_order: number; created_at: string; updated_at: string; created_by: string | null };
type ShiftRow = { id: string; day_of_week: number; initials: string; name: string; role: string; time_description: string | null; location: string; week_start: string; created_at: string; created_by: string | null };
type ComplianceRow = { id: string; requirement: string; category: string; agency: string; reference_number: string | null; frequency: string; responsible_person: string; estimated_cost: string | null; actual_cost: string | null; status: string; expires_on: string | null; created_at: string; updated_at: string; created_by: string | null };
type RecruitmentRoleRow = { id: string; title: string; type: string; applicant_count: number; is_open: boolean; description: string | null; created_at: string; updated_at: string };
type RecruitmentCandidateRow = { id: string; role_id: string | null; initials: string; name: string; role_applied: string; notes: string | null; source: string | null; stage: string; created_at: string; updated_at: string };
type RecruitmentHireRow = { id: string; initials: string; name: string; role: string; tasks_done: number; tasks_total: number; status: string; created_at: string; updated_at: string };
type RecruitmentDepartureRow = { id: string; initials: string; name: string; role: string; tasks_done: number; tasks_total: number; status: string; created_at: string; updated_at: string };
type PerformanceReviewRow = { id: string; staff_id: string | null; initials: string; name: string; role: string; cycle: string; rating: number | null; status: string; notes: string | null; created_at: string; updated_at: string };
type PerformanceGoalRow = { id: string; label: string; owner: string; progress_pct: number; detail: string | null; created_at: string; updated_at: string };
type PayrollEmployeeRow = { id: string; staff_id: string | null; initials: string; name: string; role: string; employee_ref: string; base_salary: number; sss_number: string | null; tin: string | null; philhealth_number: string | null; pagibig_number: string | null; status: string; hired_at: string | null; created_at: string; updated_at: string };
type PayrollRunRow = { id: string; reference: string; period_label: string; period_start: string; period_end: string; payment_date: string; employee_count: number; prepared_by: string; gross_total: number; deductions_total: number; employer_share: number; net_total: number; steps_done: number; steps_total: number; status: string; created_at: string; updated_at: string; created_by: string | null };
type PayrollPayslipRow = { id: string; run_id: string; employee_id: string; initials: string; name: string; role: string; basic_pay: number; overtime_pay: number; gross_pay: number; sss_ee: number; philhealth_ee: number; pagibig_ee: number; withholding_tax: number; other_deductions: number; net_pay: number; created_at: string };
type PayrollAdjustmentRow = { id: string; employee_id: string; amount: number; reason: string; effective_date: string; approved_at: string | null; approved_by: string | null; status: string; created_at: string };
type PayrollContributionRow = { id: string; employee_id: string; period_label: string; sss_amount: number; philhealth_amount: number; pagibig_amount: number; employer_sss: number; employer_philhealth: number; employer_pagibig: number; paid_at: string | null; created_at: string };
type WebsitePortfolioRow = { id: string; slot: string; title: string; category: string; consent_reference: string | null; media_asset_id: string | null; status: string; created_at: string; updated_at: string };
type StaffAuditLogRow = { id: number; actor_id: string | null; actor_name: string; event: string; event_type: string; entity_type: string | null; entity_id: string | null; metadata: Json | null; ip_address: string | null; created_at: string };
type ExpenseRow = { id: string; reference: string; vendor_name_snapshot: string; category_id: string; category: string; description: string; expense_date: string; amount_php: number; subtotal_amount_centavos: number; tax_amount_centavos: number; total_amount_centavos: number; currency: string; payment_source_id: string | null; payment_method: string | null; paid_by_type: string; paid_by_user_id: string | null; payment_date: string | null; transaction_reference: string | null; status: string; receipt_status: string; receipt_exception_reason: string | null; internal_note: string | null; invoice_number: string | null; receipt_number: string | null; approval_request_id: string | null; recurring_template_id: string | null; reimbursement_state: string; owner_funded: boolean; duplicate_of: string | null; duplicate_suspected: boolean; submitted_by: string | null; submitted_at: string | null; approved_by: string | null; approved_at: string | null; payment_recorded_at: string | null; version: number; voided_at: string | null; created_by: string | null; created_at: string; updated_at: string };
type ExpenseCategoryRow = { id: string; name: string; reporting_group: string; active: boolean; requires_project: boolean; receipt_threshold_centavos: number | null; created_by: string | null; created_at: string; updated_at: string };
type ExpensePaymentSourceRow = { id: string; code: string; name: string; method: string; source_type: string; active: boolean; created_by: string | null; created_at: string; updated_at: string };
type ExpenseAllocationRow = { id: string; expense_id: string; allocation_type: string; project_id: string | null; booking_id: string | null; equipment_id: string | null; maintenance_record_id: string | null; amount_centavos: number; created_by: string | null; created_at: string };
type ExpenseAttachmentRow = { id: string; expense_id: string; media_asset_id: string; document_type: string; verification_status: string; uploaded_by: string | null; created_at: string; removed_at: string | null; removed_by: string | null };
type ExpenseReviewRow = { id: number; expense_id: string; actor_id: string | null; action: string; previous_status: string | null; new_status: string | null; reason: string | null; previous_data: Json; new_data: Json; metadata: Json; created_at: string };
type ReimbursementClaimRow = { id: string; expense_id: string; staff_id: string; approval_request_id: string | null; requested_amount_centavos: number; approved_amount_centavos: number | null; payout_status: string; requested_payout_method: string | null; financial_event_id: string | null; paid_at: string | null; created_at: string; updated_at: string };
type OwnerAdvanceRow = { id: string; expense_id: string; funder_id: string; amount_advanced_centavos: number; amount_repaid_centavos: number; status: string; funded_at: string; created_at: string };
type OwnerAdvanceRepaymentRow = { id: string; owner_advance_id: string; payment_source_id: string; amount_centavos: number; transaction_reference: string; idempotency_key: string; paid_at: string; recorded_by: string; created_at: string };
type RecurringExpenseTemplateRow = { id: string; vendor_name_snapshot: string; category_id: string; expected_amount_centavos: number; frequency: string; next_due_date: string; payment_source_id: string | null; default_allocation: Json; receipt_required: boolean; state: string; start_date: string; end_date: string | null; reminder_days: number; created_by: string; created_at: string; updated_at: string };
type SavedReportRow = { id: string; name: string; source: string; period: string; schedule: string; created_by: string | null; created_at: string };
export type ApprovalRequestRow = { id: string; reference: string; request_type: string; subject: string; description: string; priority: string; status: string; fulfillment_status: string | null; requester_id: string; current_approver_id: string | null; workflow_rule_id: string | null; source_module: string; source_record_id: string | null; source_reference: string | null; project_id: string | null; booking_id: string | null; client_id: string | null; employee_id: string | null; amount_php: number | null; currency: string; required_by: string | null; details: Json; notes_to_approver: string | null; idempotency_key: string; submitted_at: string | null; approved_at: string | null; rejected_at: string | null; withdrawn_at: string | null; completed_at: string | null; created_at: string; updated_at: string; archived_at: string | null };
type ApprovalWorkflowRuleRow = { id: string; name: string; request_type: string; min_amount_php: number | null; max_amount_php: number | null; steps: Json; bulk_approval_allowed: boolean; bulk_amount_limit_php: number | null; allow_self_super_admin: boolean; priority: number; active: boolean; created_by: string | null; created_at: string; updated_at: string };
export type ApprovalStepRow = { id: string; request_id: string; step_number: number; approver_user_id: string | null; approver_role: string | null; status: string; decision: string | null; comment: string | null; acted_by: string | null; acted_at: string | null; due_at: string | null; delegated_from: string | null; created_at: string };
type ApprovalCommentRow = { id: string; request_id: string; author_id: string; body: string; visibility: string; created_at: string; updated_at: string };
type ApprovalAttachmentRow = { id: string; request_id: string; media_asset_id: string; label: string | null; uploaded_by: string | null; created_at: string };
type ApprovalFinancialEventRow = { id: string; request_id: string; event_type: string; amount_php: number; payment_method: string; transaction_reference: string; recorded_by: string; occurred_at: string; notes: string | null; created_at: string };
type ApprovalLiquidationItemRow = { id: string; request_id: string; expense_date: string; category: string; description: string; amount_php: number; receipt_media_asset_id: string | null; created_at: string };
type ApprovalAuditRow = { id: number; request_id: string; actor_id: string | null; action: string; previous_state: Json; new_state: Json; comment: string | null; approval_step_id: string | null; metadata: Json; created_at: string };
type StaffNotificationRow = { id: string; recipient_id: string; request_id: string | null; event_key: string; kind: string; title: string; body: string; href: string; read_at: string | null; created_at: string };
type EmailTemplateRow = { id: string; template_key: string; name: string; audience: string; description: string | null; active: boolean; created_at: string; updated_at: string };
type EmailTemplateVersionRow = { id: string; template_id: string; version: number; subject_template: string; html_template: string | null; text_template: string | null; variable_schema: Json; contains_secure_content: boolean; change_note: string; published_at: string | null; created_by: string | null; created_at: string };
type TransactionalMessageRow = { id: string; template_version_id: string; environment: string; provider: string; logical_idempotency_key: string; request_fingerprint: string; resend_sequence: number; parent_message_id: string | null; status: string; client_id: string | null; recipient_profile_id: string | null; recipient_user_id: string | null; recipient_email: string; recipient_name: string | null; recipient_snapshot: Json; sender_email: string; sender_name: string | null; reply_to_email: string | null; trigger_key: string; source: string; source_reference: string | null; booking_id: string | null; invoice_id: string | null; payment_id: string | null; project_id: string | null; gallery_id: string | null; loyalty_reward_id: string | null; related_type: string | null; related_id: string | null; render_context: Json; rendered_subject: string; rendered_html: string | null; rendered_text: string | null; contains_secure_content: boolean; content_redacted: boolean; render_context_redacted: boolean; redacted_fields: string[]; retry_eligible: boolean; max_attempts: number; attempt_count: number; next_attempt_at: string; claim_token: string | null; claimed_by: string | null; claimed_at: string | null; claim_expires_at: string | null; provider_message_id: string | null; last_error_code: string | null; last_error_message: string | null; queued_at: string; accepted_at: string | null; sent_at: string | null; delivered_at: string | null; failed_at: string | null; cancelled_at: string | null; created_at: string; updated_at: string };
type TransactionalMessageAttemptRow = { id: number; message_id: string; attempt_number: number; provider: string; worker_id: string; outcome: string; provider_message_id: string | null; error_code: string | null; error_message: string | null; retryable: boolean; started_at: string; finished_at: string; duration_ms: number | null; response_metadata: Json; response_metadata_redacted: boolean };
type TransactionalMessageEventRow = { id: number; message_id: string; environment: string; provider: string; provider_event_id: string | null; provider_message_id: string | null; event_type: string; mapped_status: string | null; occurred_at: string; received_at: string; payload: Json; payload_redacted: boolean };
type LegalDocumentRow = { id: string; document_key: string; title: string; description: string | null; created_at: string; updated_at: string };
type LegalDocumentVersionRow = { id: string; legal_document_id: string; version_number: number; version_label: string; title: string; summary: Json; effective_date: string | null; state: string; content: Json; content_hash: string; change_summary: string; created_by: string | null; approved_by: string | null; approved_at: string | null; published_by: string | null; published_at: string | null; created_at: string; updated_at: string };
type AgreementAcceptanceRow = { id: string; booking_id: string; client_id: string; client_profile_id: string; accepted_by_user_id: string | null; legal_document_version_id: string; legal_document_id: string; version_number: number; document_hash: string; accepted_at: string; method: string; source: string; environment: string; locale: string | null; idempotency_key: string; booking_snapshot: Json; client_snapshot: Json; profile_snapshot: Json; user_snapshot: Json; booking_summary: Json; booking_summary_hash: string; evidence_metadata: Json; created_at: string };
type BookingAgreementRequirementRow = { booking_id: string; client_id: string; legal_document_version_id: string | null; status: string; acceptance_id: string | null; required_at: string | null; accepted_at: string | null; created_at: string; updated_at: string };
type ConsentRecordRow = { id: string; booking_id: string; client_id: string; client_profile_id: string; user_id: string | null; purpose: string; selected: boolean; recorded_at: string; source: string; locale: string | null; idempotency_key: string; selection_metadata: Json; withdrawal_of: string | null; withdrawal_metadata: Json; created_at: string };
type PromoCodeRow = { id: string; code: string; label: string; description: string | null; type: string; value: number; currency: string; status: string; usage_limit: number | null; usage_count: number; max_uses_per_customer: number | null; valid_from: string; valid_until: string | null; applicable_services: string[]; excluded_services: string[]; minimum_booking_amount: number | null; maximum_discount_amount: number | null; created_by: string; created_at: string; updated_at: string };
type PromoCodeUsageRow = { id: string; promo_code_id: string; booking_id: string; client_id: string; discount_amount: number; used_at: string };

export type Database = {
  public: {
    Tables: {
      clients: Table<ClientRow>;
      client_profiles: Table<ProfileRow>;
      bookings: Table<BookingRow>;
      projects: Table<ProjectRow>;
      invoices: Table<InvoiceRow>;
      payments: Table<PaymentRow>;
      payment_line_items: Table<PaymentLineItemRow>;
      payment_allocations: Table<PaymentAllocationRow>;
      invoice_items: Table<InvoiceItemRow>;
      cash_transactions: Table<CashTransactionRow>;
      receipts: Table<ReceiptRow>;
      receipt_line_items: Table<ReceiptLineItemRow>;
      payment_events: Table<PaymentEventRow>;
      payment_settlements: Table<PaymentSettlementRow>;
      inventory_movements: Table<InventoryMovementRow>;
      locations: Table<LocationRow>;
      cash_registers: Table<CashRegisterRow>;
      cash_register_sessions: Table<CashRegisterSessionRow>;
      cash_register_session_events: Table<CashRegisterSessionEventRow>;
      cash_register_events: Table<CashRegisterEventRow>;
      payment_refunds: Table<PaymentRefundRow>;
      galleries: Table<GalleryRow>;
      gallery_assets: Table<GalleryAssetRow>;
      media_assets: Table<MediaAssetRow>;
      gallery_favorites: Table<GalleryFavoriteRow>;
      gallery_selections: Table<GallerySelectionRow>;
      gallery_activity: Table<GalleryActivityRow>;
      media_upload_sessions: Table<MediaUploadSessionRow>;
      media_processing_jobs: Table<MediaProcessingJobRow>;
      gallery_download_archives: Table<GalleryDownloadArchiveRow>;
      gallery_email_outbox: Table<GalleryEmailOutboxRow>;
      customer_messages: Table<MessageRow>;
      customer_audit_log: Table<AuditRow>;
      customer_identity_resolution_cases: Table<ResolutionRow>;
      customer_auth_rate_limits: Table<RateLimitRow>;
      staff_profiles: Table<StaffProfileRow>;
      staff_emergency_contacts: Table<StaffEmergencyContactRow>;
      staff_recovery_emails: Table<StaffRecoveryEmailRow>;
      services: Table<ServiceRow>;
      booking_resources: Table<BookingResourceRow>;
      booking_reservations: Table<BookingReservationRow>;
      loyalty_programs: Table<LoyaltyProgramRow>;
      loyalty_rewards: Table<LoyaltyRewardRow>;
      loyalty_booking_eligibility: Table<LoyaltyEligibilityRow>;
      loyalty_booking_events: Table<LoyaltyEventRow>;
      loyalty_email_outbox: Table<LoyaltyOutboxRow>;
      loyalty_terms_versions: Table<LoyaltyTermsRow>;
      loyalty_audit_log: Table<LoyaltyAuditRow>;
      products: Table<ProductRow>;
      pos_sales: Table<PosSaleRow>;
      pos_sale_items: Table<PosSaleItemRow>;
      pos_catalogs: Table<PosCatalogRow>;
      pos_catalog_items: Table<PosCatalogItemRow>;
      equipment: Table<EquipmentRow>;
      equipment_checkouts: Table<EquipmentCheckoutRow>;
      maintenance_records: Table<MaintenanceRow>;
      marketing_campaigns: Table<MarketingCampaignRow>;
      quotations: Table<QuotationRow>;
      glitches: Table<GlitchRow>;
      glitch_activity: Table<GlitchActivityRow>;
      glitch_attachments: Table<GlitchAttachmentRow>;
      feedback_reports: Table<FeedbackReportRow>;
      tasks: Table<TaskRow>;
      shifts: Table<ShiftRow>;
      compliance_records: Table<ComplianceRow>;
      recruitment_roles: Table<RecruitmentRoleRow>;
      recruitment_candidates: Table<RecruitmentCandidateRow>;
      recruitment_hires: Table<RecruitmentHireRow>;
      recruitment_departures: Table<RecruitmentDepartureRow>;
      performance_reviews: Table<PerformanceReviewRow>;
      performance_goals: Table<PerformanceGoalRow>;
      payroll_employees: Table<PayrollEmployeeRow>;
      payroll_runs: Table<PayrollRunRow>;
      payroll_payslips: Table<PayrollPayslipRow>;
      payroll_adjustments: Table<PayrollAdjustmentRow>;
      payroll_contributions: Table<PayrollContributionRow>;
      website_portfolio_items: Table<WebsitePortfolioRow>;
      staff_audit_log: Table<StaffAuditLogRow>;
      expenses: Table<ExpenseRow>;
      expense_categories: Table<ExpenseCategoryRow>;
      expense_payment_sources: Table<ExpensePaymentSourceRow>;
      expense_allocations: Table<ExpenseAllocationRow>;
      expense_attachments: Table<ExpenseAttachmentRow>;
      expense_reviews: Table<ExpenseReviewRow>;
      reimbursement_claims: Table<ReimbursementClaimRow>;
      owner_advances: Table<OwnerAdvanceRow>;
      owner_advance_repayments: Table<OwnerAdvanceRepaymentRow>;
      recurring_expense_templates: Table<RecurringExpenseTemplateRow>;
      saved_reports: Table<SavedReportRow>;
      approval_workflow_rules: Table<ApprovalWorkflowRuleRow>;
      approval_requests: Table<ApprovalRequestRow>;
      approval_steps: Table<ApprovalStepRow>;
      approval_comments: Table<ApprovalCommentRow>;
      approval_attachments: Table<ApprovalAttachmentRow>;
      approval_financial_events: Table<ApprovalFinancialEventRow>;
      approval_liquidation_items: Table<ApprovalLiquidationItemRow>;
      approval_audit_log: Table<ApprovalAuditRow>;
      staff_notifications: Table<StaffNotificationRow>;
      email_templates: Table<EmailTemplateRow>;
      email_template_versions: Table<EmailTemplateVersionRow>;
      transactional_messages: Table<TransactionalMessageRow>;
      transactional_message_attempts: Table<TransactionalMessageAttemptRow>;
      transactional_message_events: Table<TransactionalMessageEventRow>;
      legal_documents: Table<LegalDocumentRow>;
      legal_document_versions: Table<LegalDocumentVersionRow>;
      agreement_acceptances: Table<AgreementAcceptanceRow>;
      booking_agreement_requirements: Table<BookingAgreementRequirementRow>;
      consent_records: Table<ConsentRecordRow>;
      promo_codes: Table<PromoCodeRow>;
      promo_code_usages: Table<PromoCodeUsageRow>;
    };
    Views: Record<string, never>;
    Functions: {
      consume_customer_auth_rate_limit: {
        Args: { requested_scope: string; requested_key_hash: string; maximum_attempts: number; window_duration: string };
        Returns: Array<{ allowed: boolean; attempts: number; retry_at: string }>;
      };
      customer_owns_client: { Args: { requested_client_id: string }; Returns: boolean };
      claim_booking_checkout: { Args: { requested_booking_id: string }; Returns: boolean };
      expire_booking_holds: { Args: { requested_limit?: number }; Returns: number };
      get_booking_availability: { Args: { requested_service_id: string; requested_date: string; requested_resource_id?: string | null; requested_duration_minutes?: number | null }; Returns: Json };
      acquire_booking_hold: { Args: { requested_service_id: string; requested_starts_at: string; requested_idempotency_key: string; requested_fingerprint: string; requested_owner_token_hash: string; requested_resource_id?: string | null; requested_hold_minutes?: number | null; requested_duration_minutes?: number | null }; Returns: Json };
      release_booking_hold: { Args: { requested_reservation_id: string; requested_owner_token_hash: string }; Returns: Json };
      link_booking_hold: { Args: { requested_booking_id: string; requested_reservation_id: string; requested_owner_token_hash: string }; Returns: Json };
      activate_booking_checkout: { Args: { requested_booking_id: string; requested_checkout_session_id: string; requested_checkout_url: string; requested_checkout_expires_at: string }; Returns: Json };
      release_failed_booking_checkout: { Args: { requested_booking_id: string; requested_checkout_session_id: string; requested_payment_status: string }; Returns: Json };
      get_booking_calendar_reservations: { Args: { requested_starts_at: string; requested_ends_at: string }; Returns: Json };
      reschedule_booking: { Args: { requested_reference: string; requested_date: string; requested_time: string; requested_resource_id: string; requested_actor_id: string; requested_reason: string }; Returns: BookingRow };
      update_booking_status: { Args: { requested_reference: string; requested_status: string; requested_actor_id: string; requested_reason: string }; Returns: BookingRow };
      extend_booking_hold_for_checkout: { Args: { requested_booking_id: string; requested_expires_at: string }; Returns: Json };
      expire_legacy_paymongo_booking: { Args: { requested_checkout_id: string; requested_reason: string }; Returns: BookingRow };
      enqueue_provider_webhook_event: { Args: { requested_provider: string; requested_event_id: string; requested_event_type: string; requested_fingerprint: string; requested_safe_payload?: Json }; Returns: Json };
      finish_provider_webhook_event: { Args: { requested_provider: string; requested_event_id: string; requested_succeeded: boolean; requested_last_error?: string | null }; Returns: Json };
      create_linked_booking_pair: { Args: { requested_studio: Json; requested_event: Json }; Returns: Json };
      accept_booking_agreement: { Args: { requested_booking_id: string; requested_user_id: string | null; requested_version_id: string; requested_document_hash: string; requested_idempotency_key: string; requested_method: string; requested_source: string; requested_environment: string; requested_locale?: string | null; requested_evidence_metadata?: Json }; Returns: AgreementAcceptanceRow };
      legal_document_create_version: { Args: { requested_document_key: string; requested_content: Json; requested_actor_user_id: string; requested_change_summary: string }; Returns: LegalDocumentVersionRow };
      legal_document_update_draft: { Args: { requested_version_id: string; requested_content: Json; requested_actor_user_id: string; requested_change_summary: string }; Returns: LegalDocumentVersionRow };
      legal_document_transition: { Args: { requested_version_id: string; requested_state: string; requested_actor_user_id: string; requested_reason: string }; Returns: LegalDocumentVersionRow };
      legal_document_publish: { Args: { requested_version_id: string; requested_actor_user_id: string; requested_reason: string }; Returns: LegalDocumentVersionRow };
      legal_document_withdraw: { Args: { requested_version_id: string; requested_actor_user_id: string; requested_reason: string }; Returns: LegalDocumentVersionRow };
      prepare_payment_collection: { Args: { requested_booking_id: string; requested_processor: string; requested_source: string; requested_payment_method: string; requested_balance_component_centavos: number; requested_idempotency_key: string; requested_add_ons?: Json; requested_create_invoice?: boolean; requested_note?: string | null; requested_receipt?: boolean; requested_actor_id?: string | null }; Returns: Json };
      collect_cash_payment: { Args: { requested_booking_id: string; requested_processor: string; requested_source: string; requested_payment_method: string; requested_balance_component_centavos: number; requested_idempotency_key: string; requested_add_ons?: Json; requested_create_invoice?: boolean; requested_note?: string | null; requested_receipt?: boolean; requested_actor_id?: string | null; requested_cash_received_centavos?: number | null; requested_paid_at?: string }; Returns: PaymentRow };
      post_cash_payment: { Args: { requested_payment_id: string; requested_cash_received_centavos: number; requested_actor_id: string; requested_note?: string | null; requested_receipt?: boolean; requested_paid_at?: string }; Returns: PaymentRow };
      cancel_unbound_payment: { Args: { requested_payment_id: string; requested_actor_id: string }; Returns: PaymentRow };
      reconcile_failed_provider_payment: { Args: { requested_payment_id: string; requested_actor_id: string; requested_reason: string }; Returns: PaymentRow };
      mark_paymongo_checkout: { Args: { requested_payment_id: string; requested_checkout_session_id: string; requested_checkout_url: string; requested_checkout_expires_at: string; requested_payment_intent_id?: string | null }; Returns: PaymentRow };
      confirm_paymongo_payment: { Args: { requested_provider_event_id: string; requested_checkout_session_id: string; requested_metadata_payment_id: string | null; requested_provider_payment_id: string; requested_payment_intent_id: string | null; requested_amount_centavos: number; requested_paid_at: string; requested_event_occurred_at: string; requested_payment_method_detail: string | null; requested_description: string | null; requested_available_at: string | null; requested_payload: Json }; Returns: PaymentRow };
      fail_or_expire_provider_payment: { Args: { requested_provider_event_id: string; requested_checkout_session_id: string; requested_metadata_payment_id: string | null; requested_event_type: string; requested_event_occurred_at: string; requested_payload: Json }; Returns: PaymentRow };
      update_paymongo_settlement: { Args: { requested_payment_id: string; requested_provider_event_id: string; requested_provider_settlement_id: string | null; requested_status: string; requested_fee_amount_centavos: number | null; requested_net_amount_centavos: number | null; requested_available_at: string | null; requested_settled_at: string | null; requested_event_occurred_at: string; requested_payload: Json }; Returns: PaymentSettlementRow };
      get_cash_collection_registers: { Args: Record<string, never>; Returns: Array<{ register_id: string; register_code: string; register_name: string; location_id: string; location_name: string; minimum_cash_centavos: number; session_id: string | null; session_status: string | null; opened_by: string | null; opened_at: string | null; opening_amount_centavos: number | null }> };
      open_cash_register: { Args: { requested_register_id: string; requested_opening_amount_centavos: number; requested_actor_id: string; requested_note?: string | null }; Returns: CashRegisterSessionRow };
      record_manual_cash_event: { Args: { requested_session_id: string; requested_event_type: string; requested_amount_centavos: number; requested_actor_id: string; requested_reason: string; requested_idempotency_key: string }; Returns: CashRegisterEventRow };
      submit_cash_register_close: { Args: { requested_session_id: string; requested_counted_amount_centavos: number; requested_actor_id: string; requested_note?: string | null }; Returns: CashRegisterSessionRow };
      review_cash_register_close: { Args: { requested_session_id: string; requested_reviewer_id: string; requested_approve: boolean; requested_note?: string | null }; Returns: CashRegisterSessionRow };
      collect_cash_payment_with_register: { Args: { requested_register_session_id: string; requested_booking_id: string; requested_balance_component_centavos: number; requested_idempotency_key: string; requested_add_ons?: Json; requested_create_invoice?: boolean; requested_note?: string | null; requested_receipt?: boolean; requested_actor_id?: string | null; requested_cash_received_centavos?: number | null; requested_paid_at?: string }; Returns: PaymentRow };
      refund_cash_payment: { Args: { requested_payment_id: string; requested_approval_request_id: string; requested_amount_centavos: number; requested_actor_id: string; requested_idempotency_key: string; requested_reason: string; requested_register_session_id?: string | null }; Returns: PaymentRefundRow };
      loyalty_set_booking_exclusion: { Args: { requested_booking_id: string; excluded: boolean; reason: string }; Returns: BookingRow };
      loyalty_transition_reward: { Args: { requested_reward_id: string; requested_status: "available" | "reserved" | "redeemed" | "cancelled"; reason: string }; Returns: LoyaltyRewardRow };
      loyalty_issue_manual_reward: { Args: { requested_client_id: string; reason: string }; Returns: LoyaltyRewardRow };
      loyalty_correct_progress: { Args: { requested_client_id: string; requested_eligible_count: number; reason: string }; Returns: number };
      loyalty_create_reward_booking: { Args: { requested_client_id: string; requested_profile_id: string; requested_reward_id: string; requested_idempotency_key: string; requested_reference: string; requested_date: string; requested_time: string; requested_location: string }; Returns: BookingRow };
      loyalty_create_reward_booking_with_hold: { Args: { requested_client_id: string; requested_profile_id: string; requested_reward_id: string; requested_idempotency_key: string; requested_reference: string; requested_date: string; requested_time: string; requested_location: string; requested_reservation_id: string; requested_owner_token_hash: string }; Returns: BookingRow };
      loyalty_claim_email: { Args: { requested_outbox_id?: string | null }; Returns: LoyaltyOutboxRow | null };
      loyalty_finish_email: { Args: { requested_outbox_id: string; succeeded: boolean; provider_id?: string | null; failure?: string | null }; Returns: undefined };
      next_glitch_reference: { Args: Record<string, never>; Returns: string };
      approval_create_request: { Args: { requested_requester_id: string; requested_idempotency_key: string; requested_request_type: string; requested_subject: string; requested_description: string; requested_priority: string; requested_source_module: string; requested_details: Json; requested_submit: boolean; requested_required_by?: string | null; requested_amount_php?: number | null; requested_currency?: string; requested_project_id?: string | null; requested_booking_id?: string | null; requested_client_id?: string | null; requested_employee_id?: string | null; requested_source_record_id?: string | null; requested_source_reference?: string | null; requested_notes?: string | null }; Returns: ApprovalRequestRow };
      approval_submit_request: { Args: { requested_request_id: string; requested_actor_id: string; requested_comment?: string | null }; Returns: ApprovalRequestRow };
      approval_update_request: { Args: { requested_request_id: string; requested_actor_id: string; requested_subject: string; requested_description: string; requested_priority: string; requested_details: Json; requested_required_by?: string | null; requested_amount_php?: number | null; requested_notes?: string | null; requested_submit?: boolean }; Returns: ApprovalRequestRow };
      approval_decide_request: { Args: { requested_request_id: string; requested_actor_id: string; requested_action: string; requested_comment?: string | null }; Returns: ApprovalRequestRow };
      approval_add_comment: { Args: { requested_request_id: string; requested_actor_id: string; requested_body: string; requested_visibility?: string }; Returns: ApprovalCommentRow };
      approval_reassign_step: { Args: { requested_request_id: string; requested_actor_id: string; requested_target_id: string; requested_comment: string; requested_delegate?: boolean }; Returns: ApprovalRequestRow };
      approval_bulk_approve: { Args: { requested_request_ids: string[]; requested_actor_id: string; requested_comment?: string | null }; Returns: number };
      approval_withdraw_request: { Args: { requested_request_id: string; requested_actor_id: string; requested_comment?: string | null }; Returns: ApprovalRequestRow };
      approval_archive_request: { Args: { requested_request_id: string; requested_actor_id: string; requested_comment: string }; Returns: ApprovalRequestRow };
      approval_update_workflow_rule: { Args: { requested_rule_id: string; requested_actor_id: string; requested_min_amount_php: number | null; requested_max_amount_php: number | null; requested_bulk_allowed: boolean; requested_bulk_limit_php: number | null; requested_active: boolean }; Returns: ApprovalWorkflowRuleRow };
      approval_record_financial_event: { Args: { requested_request_id: string; requested_actor_id: string; requested_event_type: string; requested_amount_php: number; requested_payment_method: string; requested_transaction_reference: string; requested_occurred_at: string; requested_notes?: string | null }; Returns: ApprovalRequestRow };
      approval_enqueue_due_notifications: { Args: Record<string, never>; Returns: number };
      expense_create: { Args: { requested_actor_id: string; requested_idempotency_key: string; requested_vendor: string; requested_category_id: string; requested_description: string; requested_date: string; requested_subtotal_centavos: number; requested_tax_centavos: number; requested_payment_source_id: string | null; requested_paid_by_type: string; requested_paid_by_user_id: string | null; requested_receipt_status: string; requested_receipt_exception: string; requested_internal_note: string; requested_invoice_number: string; requested_receipt_number: string; requested_allocations: Json; requested_submit: boolean; requested_reimbursable: boolean; requested_owner_funded: boolean; requested_approval_request_id?: string | null }; Returns: ExpenseRow };
      expense_transition: { Args: { requested_expense_id: string; requested_actor_id: string; requested_expected_version: number; requested_action: string; requested_reason?: string | null }; Returns: ExpenseRow };
      owner_advance_record_repayment: { Args: { requested_owner_advance_id: string; requested_actor_id: string; requested_payment_source_id: string; requested_amount_centavos: number; requested_transaction_reference: string; requested_paid_at: string; requested_idempotency_key: string }; Returns: OwnerAdvanceRow };
      expense_schedule_reimbursement: { Args: { requested_expense_id: string; requested_actor_id: string; requested_expected_version: number }; Returns: ExpenseRow };
      expense_record_reimbursement_payment: { Args: { requested_expense_id: string; requested_actor_id: string; requested_expected_version: number; requested_payment_source_id: string; requested_transaction_reference: string; requested_paid_at: string; requested_idempotency_key: string }; Returns: ExpenseRow };
      expense_resolve_duplicate: { Args: { requested_expense_id: string; requested_actor_id: string; requested_expected_version: number; requested_action: string; requested_duplicate_of?: string | null; requested_reason?: string | null }; Returns: ExpenseRow };
      recurring_expense_create: { Args: { requested_actor_id: string; requested_vendor: string; requested_category_id: string; requested_expected_amount_centavos: number; requested_frequency: string; requested_next_due_date: string; requested_payment_source_id: string | null; requested_default_allocation: Json; requested_receipt_required: boolean; requested_start_date: string; requested_end_date?: string | null; requested_reminder_days?: number }; Returns: RecurringExpenseTemplateRow };
      recurring_expense_generate: { Args: { requested_template_id: string; requested_actor_id: string }; Returns: ExpenseRow };
      expense_update_draft: { Args: { requested_expense_id: string; requested_actor_id: string; requested_expected_version: number; requested_vendor: string; requested_category_id: string; requested_description: string; requested_date: string; requested_subtotal_centavos: number; requested_tax_centavos: number; requested_receipt_status: string; requested_receipt_exception: string; requested_internal_note: string; requested_allocations: Json; requested_submit: boolean }; Returns: ExpenseRow };
      promo_code_create: { Args: { requested_code: string; requested_label: string; requested_description: string | null; requested_type: string; requested_value: number; requested_currency: string; requested_usage_limit: number | null; requested_max_uses_per_customer: number | null; requested_valid_until: string | null; requested_applicable_services: string[]; requested_excluded_services: string[]; requested_minimum_booking_amount: number | null; requested_maximum_discount_amount: number | null; requested_actor_user_id: string }; Returns: PromoCodeRow };
      promo_code_update: { Args: { requested_id: string; requested_label: string | null; requested_description: string | null; requested_type: string | null; requested_value: number | null; requested_currency: string | null; requested_usage_limit: number | null; requested_max_uses_per_customer: number | null; requested_valid_until: string | null; requested_applicable_services: string[]; requested_excluded_services: string[]; requested_minimum_booking_amount: number | null; requested_maximum_discount_amount: number | null; requested_status: string | null; requested_actor_user_id: string }; Returns: PromoCodeRow };
      promo_code_retire: { Args: { requested_id: string; requested_actor_user_id: string }; Returns: PromoCodeRow };
      validate_promo_code: { Args: { requested_code: string; requested_client_id: string; requested_booking_amount: number; requested_service_id: string | null }; Returns: { valid: boolean; discount_amount?: number; promo_code_id?: string; error?: string } };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
