export type EmailAudience = "Client" | "Internal";

export type TransactionalEmailTemplate = {
  id: string;
  name: string;
  audience: EmailAudience;
  trigger: string;
  subject: string;
  preheader: string;
  heading: string;
  message: string;
  fields: string[];
  action?: string;
  actionLabel?: string;
};

// These are the merge fields used by the supplied HTML emails. The catalogue
// keeps their contract visible until a delivery provider is connected.
export const TRANSACTIONAL_EMAILS: TransactionalEmailTemplate[] = [
  { id: "booking-request-received", name: "Booking request received", audience: "Client", trigger: "A client submits a booking request", subject: "We received your booking request", preheader: "We've received your booking request and will be in touch within 24 hours.", heading: "Booking request received", message: "Thank you for reaching out to Kahel Studio. Our team will review your request shortly.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time"] },
  { id: "awaiting-downpayment", name: "Awaiting downpayment", audience: "Client", trigger: "A booking slot is available and needs a deposit", subject: "Complete your downpayment to secure your booking", preheader: "Your slot is almost secured. Complete your 50% downpayment to confirm.", heading: "Downpayment required", message: "Your slot is available. Complete the 50% downpayment to officially secure it.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time", "amount_paid", "payment_url"], action: "payment_url", actionLabel: "Pay Downpayment Now" },
  { id: "downpayment-received", name: "Downpayment received", audience: "Client", trigger: "A downpayment is verified", subject: "Your downpayment has been received", preheader: "Your downpayment is in and your slot is now reserved.", heading: "Downpayment received!", message: "We've received and verified your downpayment. Your slot is now reserved.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time", "package_price", "addons_total", "subtotal", "downpayment_required", "amount_paid", "balance_due", "addon_prints", "addon_frame", "addon_makeup", "addon_extra_photos"] },
  { id: "booking-confirmed", name: "Booking confirmed", audience: "Client", trigger: "A booking is confirmed after payment verification", subject: "Your Kahel Studio booking is confirmed", preheader: "Your booking is confirmed. Here are all the details you need.", heading: "Your booking is confirmed!", message: "Everything is set. We look forward to shooting with you.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time", "package_price", "addons_total", "subtotal", "downpayment_required", "amount_paid", "balance_due", "addon_prints", "addon_frame", "addon_makeup", "addon_extra_photos", "google_maps_url", "google_maps_qr_url", "wifi_qr_url", "agree_url", "decline_url", "reschedule_url"], action: "agree_url", actionLabel: "Review booking policy" },
  { id: "booking-reminder", name: "Booking reminder", audience: "Client", trigger: "48 hours before a confirmed session", subject: "Your Kahel Studio session is in 48 hours", preheader: "Your session is in 48 hours. Here's everything you need to know.", heading: "Your session is in 48 hours!", message: "This is a friendly reminder that your session is coming up soon.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time", "balance_due", "google_maps_url", "google_maps_qr_url", "wifi_qr_url", "reschedule_url"], action: "reschedule_url", actionLabel: "View Available Slots" },
  { id: "balance-reminder", name: "Balance reminder", audience: "Client", trigger: "Before a session with an outstanding balance", subject: "Reminder: your session balance is due on arrival", preheader: "Your session balance is due on arrival. Here's what you need to know.", heading: "Balance due reminder", message: "Your session is coming up and the outstanding balance is due on arrival.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time", "amount_paid", "balance_due"] },
  { id: "reschedule-request", name: "Reschedule request received", audience: "Client", trigger: "A client requests a new session date", subject: "We've received your reschedule request", preheader: "We'll confirm your reschedule request within 24 hours.", heading: "Reschedule request received", message: "We'll review availability and get back to you within 24 hours.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time"] },
  { id: "reschedule-confirmed", name: "Reschedule confirmed", audience: "Client", trigger: "A new session date is approved", subject: "Your Kahel Studio session has been rescheduled", preheader: "Your session has been rescheduled. Here are your updated details.", heading: "Reschedule confirmed!", message: "Your session has been successfully rescheduled. Here are the updated details.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time", "amount_paid", "balance_due"] },
  { id: "client-cancellation", name: "Client initiated cancellation", audience: "Client", trigger: "A client cancels their booking", subject: "Your Kahel Studio booking has been cancelled", preheader: "Your booking has been cancelled as requested. Here's what happens next.", heading: "Your booking has been cancelled", message: "We've received your cancellation request and your booking has been cancelled.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time", "amount_paid"], action: "https://www.kahelstudio.com/book", actionLabel: "Book a New Session" },
  { id: "booking-cancelled", name: "Booking cancelled", audience: "Client", trigger: "A booking cancellation is recorded", subject: "Your Kahel Studio booking has been cancelled", preheader: "Your Kahel Studio booking has been cancelled. Here's what you need to know.", heading: "Your booking has been cancelled", message: "We're sorry to see you go. Your booking has been cancelled as requested.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time"], action: "https://www.kahelstudio.com/book", actionLabel: "Book a New Session" },
  { id: "kahel-cancellation", name: "Cancellation by Kahel Studio", audience: "Client", trigger: "Kahel Studio needs to cancel a booking", subject: "Important: your Kahel Studio booking has been cancelled", preheader: "We sincerely apologise. A full refund is on its way.", heading: "We need to cancel your booking", message: "We are unable to fulfil your upcoming booking and sincerely apologise for the inconvenience.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time", "cancellation_reason"], action: "https://www.kahelstudio.com/book", actionLabel: "Book a New Session" },
  { id: "refund-approved", name: "Refund approved", audience: "Client", trigger: "A refund request is approved", subject: "Your Kahel Studio refund has been approved", preheader: "Your refund has been approved. Allow 3-5 business days to process.", heading: "Refund approved", message: "Your refund request has been reviewed and approved.", fields: ["booking_id", "customer_name", "service_name", "amount_paid"] },
  { id: "waitlist-confirmation", name: "Waitlist confirmation", audience: "Client", trigger: "A requested date is full and the client joins the waitlist", subject: "You're on the Kahel Studio waitlist", preheader: "You're on the waitlist. We'll notify you as soon as a slot opens up.", heading: "You're on the waitlist!", message: "The requested date is fully booked, but you've been added to our waitlist.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "waitlist_position"], action: "https://www.kahelstudio.com/book", actionLabel: "View Available Dates" },
  { id: "waitlist-slot-available", name: "Waitlist slot available", audience: "Client", trigger: "A slot opens for a waitlisted client", subject: "A Kahel Studio slot is now available", preheader: "Great news. A slot has opened up. Act fast to secure your booking.", heading: "Your waitlist slot is available!", message: "A slot has opened for your requested session. You have 24 hours to claim it.", fields: ["booking_id", "customer_name", "service_name", "booking_date", "booking_time", "slot_expiry", "confirm_url", "browse_url"], action: "confirm_url", actionLabel: "Confirm My Booking" },
  { id: "thank-you-after-session", name: "Thank you after session", audience: "Client", trigger: "A session is completed", subject: "Thank you for shooting with Kahel Studio", preheader: "Thank you for shooting with us. Your photos are now being edited.", heading: "Thank you for the session!", message: "It was an absolute pleasure working with you. Your photos are now being carefully edited.", fields: ["booking_id", "customer_name", "service_name", "booking_date"] },
  { id: "rebooking-offer", name: "Rebooking offer", audience: "Client", trigger: "A follow-up campaign after a previous session", subject: "We'd love to shoot with you again", preheader: "Book your next session with Kahel Studio.", heading: "We'd love to shoot with you again!", message: "It's been a while since your last session. We'd love to create more memories together.", fields: ["customer_name", "service_name", "booking_date"], action: "https://www.kahelstudio.com/book", actionLabel: "Book Your Next Session" },
  { id: "internal-new-booking", name: "Internal new booking request", audience: "Internal", trigger: "A client submits a booking request", subject: "New booking request: {{ booking_id }}", preheader: "New booking request received. Action required.", heading: "New booking request received", message: "A new booking request is awaiting review.", fields: ["customer_name", "booking_id", "service_name", "booking_date", "booking_time", "customer_email", "customer_phone", "submitted_at"], action: "https://dashboard.kahelstudio.com/bookings", actionLabel: "Review Booking in Dashboard" },
  { id: "internal-payment-received", name: "Internal payment received", audience: "Internal", trigger: "A payment is verified", subject: "Payment received: {{ booking_id }}", preheader: "Payment received and verified. Confirm the booking.", heading: "Payment received", message: "A payment has been successfully received and verified.", fields: ["customer_name", "booking_id", "service_name", "booking_date", "amount_paid", "balance_due", "payment_method", "transaction_id"], action: "https://dashboard.kahelstudio.com/bookings", actionLabel: "View Booking in Dashboard" },
  { id: "internal-reschedule-request", name: "Internal reschedule request", audience: "Internal", trigger: "A client requests a new session date", subject: "Reschedule request: {{ booking_id }}", preheader: "Reschedule request received. Review and confirm.", heading: "Reschedule request received", message: "A client has requested to reschedule their booking.", fields: ["customer_name", "booking_id", "service_name", "booking_date", "booking_time", "new_date", "new_time", "customer_email"], action: "https://dashboard.kahelstudio.com/bookings", actionLabel: "Review in Dashboard" },
  { id: "internal-no-show", name: "Internal no show alert", audience: "Internal", trigger: "A client is marked as a no show", subject: "No show alert: {{ booking_id }}", preheader: "No show alert. The client did not attend their session.", heading: "Client no show", message: "A client did not attend their scheduled session today.", fields: ["customer_name", "booking_id", "service_name", "booking_date", "booking_time", "amount_paid", "customer_email", "customer_phone"], action: "https://dashboard.kahelstudio.com/bookings", actionLabel: "Update Booking Status" },
];
