"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { AlertTriangle, FileUp, Link2, RotateCcw, X } from "lucide-react";
import { GLITCH_CATEGORIES, GLITCH_SEVERITIES, GLITCH_STATUSES } from "@/lib/glitches";
import type { GlitchOption, GlitchRecord, GlitchesWorkspace } from "@/lib/server/glitches-data";
import type { useToast } from "@/components/toast/toast-provider";
import { formatGlitchDate, glitchSeverityTone, glitchStatusTone } from "./glitch-presentation";

type FireToast = ReturnType<typeof useToast>["fireToast"];
type AttachmentDownload = { id: string; filename: string; url: string | null };

export function ReportGlitchDialog({ workspace, close, refresh, fireToast }: { workspace: GlitchesWorkspace; close: () => void; refresh: () => Promise<void>; fireToast: FireToast }) {
  const [submitting, setSubmitting] = useState(false), [error, setError] = useState(""), [files, setFiles] = useState<File[]>([]); const titleRef = useRef<HTMLInputElement>(null);
  useEffect(() => { titleRef.current?.focus(); const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !submitting) close(); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [close, submitting]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (submitting) return; setSubmitting(true); setError("");
    const form = new FormData(event.currentTarget);
    const payload = Object.fromEntries(["title", "description", "category", "severity", "locationOrSystem", "observedAt", "assignedTo", "bookingId", "projectId", "clientId", "workaround"].map((key) => [key, form.get(key)]));
    try {
      const response = await fetch("/api/glitches", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...payload, operationsBlocked: form.get("operationsBlocked") === "on", observedAt: new Date(String(payload.observedAt)).toISOString() }) });
      const result = await response.json() as { id?: string; reference?: string; error?: string }; if (!response.ok || !result.id) throw new Error(result.error ?? "Unable to report the glitch.");
      for (const file of files) { const upload = new FormData(); upload.set("file", file); const uploaded = await fetch(`/api/glitches/${result.id}/attachments`, { method: "POST", body: upload }); if (!uploaded.ok) throw new Error(`Glitch reported, but ${file.name} could not be attached.`); }
      await refresh(); close(); fireToast(`${result.reference} reported`, "success");
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to report the glitch."); }
    finally { setSubmitting(false); }
  }
  return <DialogFrame title="Report Glitch" subtitle="Record an operational incident for investigation." close={close} locked={submitting}><form onSubmit={submit}><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Issue title" className="sm:col-span-2"><input ref={titleRef} name="title" required minLength={3} maxLength={200} className="glitch-input" /></Field><Field label="Description" className="sm:col-span-2"><textarea name="description" required minLength={5} maxLength={5000} rows={4} className="glitch-input h-auto py-2.5" /></Field><SelectField label="Category" name="category" options={GLITCH_CATEGORIES} defaultValue="System" /><SelectField label="Severity" name="severity" options={GLITCH_SEVERITIES} defaultValue="Medium" /><Field label="Location or affected system"><input name="locationOrSystem" maxLength={255} className="glitch-input" /></Field><Field label="Date and time observed"><input name="observedAt" required type="datetime-local" defaultValue={localDateTime()} className="glitch-input" /></Field><OptionField label="Assigned to" name="assignedTo" options={workspace.staff.map((item) => ({ id: item.id, label: item.name }))} /><OptionField label="Related booking" name="bookingId" options={workspace.bookings} /><OptionField label="Related project" name="projectId" options={workspace.projects} /><OptionField label="Related client" name="clientId" options={workspace.clients} /><Field label="Temporary workaround" className="sm:col-span-2"><textarea name="workaround" maxLength={2000} rows={2} className="glitch-input h-auto py-2.5" /></Field><Field label="Attachments or screenshots" className="sm:col-span-2"><input type="file" multiple accept="image/jpeg,image/png,image/webp,application/pdf,text/plain" onChange={(event) => setFiles(Array.from(event.target.files ?? []))} className="block w-full text-sm file:mr-3 file:rounded-control file:border-0 file:bg-[var(--color-surface-muted)] file:px-3 file:py-2 file:font-semibold" /><span className="mt-1 block text-xs font-normal text-[var(--color-text-muted)]">Up to 10 MB each. JPEG, PNG, WebP, PDF, or text.</span></Field><label className="flex items-center gap-3 sm:col-span-2"><input type="checkbox" name="operationsBlocked" className="h-4 w-4 accent-[#FF5300]" /><span className="text-sm font-semibold">Operations currently blocked</span></label>{error ? <p role="alert" className="text-sm font-semibold text-[var(--color-danger-text)] sm:col-span-2">{error}</p> : null}</div><DialogActions close={close} submitting={submitting} label="Report Glitch" /></form></DialogFrame>;
}

export function GlitchDetailDrawer({ glitch, workspace, close, refresh, fireToast }: { glitch: GlitchRecord; workspace: GlitchesWorkspace; close: () => void; refresh: () => Promise<void>; fireToast: FireToast }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [edit, setEdit] = useState(false), [attachments, setAttachments] = useState<AttachmentDownload[]>([]);
  const admin = workspace.viewer.role !== "staff", assigned = glitch.assignedToId === workspace.viewer.id;
  useEffect(() => { const key = (event: KeyboardEvent) => { if (event.key === "Escape" && !busy) close(); }; window.addEventListener("keydown", key); return () => window.removeEventListener("keydown", key); }, [busy, close]);
  useEffect(() => { void loadAttachments(glitch.id).then(setAttachments); }, [glitch.id]);
  async function mutate(action: string, body: Record<string, unknown> = {}) { setBusy(true); setError(""); try { const response = await fetch(`/api/glitches/${glitch.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, ...body }) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error); await refresh(); fireToast("Glitch updated", "success"); return true; } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update the glitch."); return false; } finally { setBusy(false); } }
  async function upload(file: File | undefined) { if (!file) return; setBusy(true); const form = new FormData(); form.set("file", file); try { const response = await fetch(`/api/glitches/${glitch.id}/attachments`, { method: "POST", body: form }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error); await refresh(); setAttachments(await loadAttachments(glitch.id)); fireToast("Attachment added", "success"); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to upload attachment."); } finally { setBusy(false); } }
  return <div className="fixed inset-0 z-50 bg-black/40" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) close(); }}><aside role="dialog" aria-modal="true" aria-labelledby="glitch-detail-title" className="absolute inset-y-0 right-0 w-full max-w-2xl overflow-y-auto border-l border-[var(--color-border)] bg-[var(--color-surface)] shadow-[var(--shadow-dialog)]"><header className="sticky top-0 z-10 flex items-start gap-4 border-b border-[var(--color-border)] bg-[var(--color-surface)] p-5"><div className="min-w-0"><div className="text-xs font-semibold text-[var(--color-text-muted)]">{glitch.reference}</div><h2 id="glitch-detail-title" className="mt-1 truncate font-display text-xl font-semibold">{glitch.title}</h2><div className="mt-2 flex flex-wrap gap-2"><span className={`rounded-pill px-2.5 py-1 text-[11px] font-semibold ${glitchStatusTone[glitch.status]}`}>{glitch.status}</span><span className={`rounded-pill bg-[var(--color-surface-muted)] px-2.5 py-1 text-[11px] font-semibold ${glitchSeverityTone[glitch.severity]}`}>{glitch.severity}</span><span className="rounded-pill bg-[var(--color-surface-muted)] px-2.5 py-1 text-[11px] font-semibold">{glitch.category}</span></div></div><button onClick={close} disabled={busy} className="ml-auto grid min-h-11 min-w-11 place-items-center rounded-control hover:bg-[var(--color-surface-muted)]" aria-label="Close details"><X className="h-4 w-4" /></button></header><div className="space-y-6 p-5">
    {error ? <p role="alert" className="rounded-control bg-[var(--color-danger-bg)] p-3 text-sm font-semibold text-[var(--color-danger-text)]">{error}</p> : null}
    {edit ? <EditForm glitch={glitch} admin={admin} cancel={() => setEdit(false)} submit={async (body) => { if (await mutate("edit", body)) setEdit(false); }} busy={busy} /> : <Incident glitch={glitch} editable={admin || assigned} edit={() => setEdit(true)} />}
    <section><SectionTitle title="Actions" />{admin ? <div className="grid gap-3 sm:grid-cols-2"><ActionSelect label="Assign or reassign" value={glitch.assignedToId ?? ""} options={workspace.staff.map((item) => ({ id: item.id, label: item.name }))} change={(assignedTo) => void mutate("assign", { assignedTo })} disabled={busy} /><ActionSelect label="Change status" value={glitch.status} options={GLITCH_STATUSES.filter((item) => !["Resolved", "Closed"].includes(item)).map((item) => ({ id: item, label: item }))} change={(status) => void mutate("status", { status })} disabled={busy} /></div> : assigned ? <ActionSelect label="Change status" value={glitch.status} options={["Open", "In Progress", "Waiting"].map((item) => ({ id: item, label: item }))} change={(status) => void mutate("status", { status })} disabled={busy} /> : null}{admin ? <TaskActions workspace={workspace} glitch={glitch} mutate={mutate} busy={busy} /> : null}</section>
    <section><SectionTitle title="Attachments" /><div className="space-y-2">{attachments.map((item) => item.url ? <a key={item.id} href={item.url} target="_blank" rel="noreferrer" className="flex min-h-11 items-center gap-2 rounded-control border border-[var(--color-border)] px-3 text-sm font-semibold"><FileUp className="h-4 w-4" /> {item.filename}</a> : <div key={item.id} className="text-sm text-[var(--color-text-muted)]">{item.filename}</div>)}{!attachments.length ? <p className="text-sm text-[var(--color-text-muted)]">No attachments.</p> : null}</div><label className="mt-3 inline-flex min-h-11 cursor-pointer items-center gap-2 rounded-control border border-[var(--color-border)] px-3 text-sm font-semibold"><FileUp className="h-4 w-4" /> Add attachment<input type="file" className="sr-only" disabled={busy} accept="image/jpeg,image/png,image/webp,application/pdf,text/plain" onChange={(event) => void upload(event.target.files?.[0])} /></label></section>
    <UpdateForm submit={(message) => mutate("internal_update", { message })} busy={busy} />
    {admin && !["Resolved", "Closed"].includes(glitch.status) ? <ResolveForm submit={(resolutionSummary, resolvedAt) => mutate("resolve", { resolutionSummary, resolvedAt: new Date(resolvedAt).toISOString() })} busy={busy} /> : null}
    {admin && ["Resolved", "Closed"].includes(glitch.status) ? <ReopenForm submit={(reason) => mutate("reopen", { reason })} busy={busy} /> : null}
    {admin && glitch.status === "Resolved" ? <button onClick={() => void mutate("close")} disabled={busy} className="h-11 rounded-control border border-[var(--color-border)] px-4 text-sm font-semibold">Close glitch</button> : null}
    {glitch.resolutionSummary ? <section><SectionTitle title="Resolution" /><p className="whitespace-pre-wrap text-sm text-[var(--color-text-secondary)]">{glitch.resolutionSummary}</p><p className="mt-2 text-xs text-[var(--color-text-muted)]">Resolved {glitch.resolvedAt ? formatGlitchDate(glitch.resolvedAt) : "—"} by {glitch.resolvedBy ?? "Former staff member"}{glitch.closedAt ? ` · Closed ${formatGlitchDate(glitch.closedAt)}` : ""}</p></section> : null}
    <section><SectionTitle title="Activity" /><ol className="space-y-4 border-l border-[var(--color-border)] pl-4">{glitch.activities.map((event) => <li key={event.id}><p className="text-sm font-medium">{event.message}</p><p className="mt-1 text-xs text-[var(--color-text-muted)]">{event.actor} · {formatGlitchDate(event.createdAt)}</p></li>)}</ol></section>
    {workspace.viewer.role === "super_admin" ? <button onClick={() => { if (window.confirm("Archive this glitch? It will leave normal views but retain its history.")) void mutate("archive").then((ok) => { if (ok) close(); }); }} disabled={busy} className="text-sm font-semibold text-[var(--color-danger-text)] underline">Archive glitch</button> : null}
  </div></aside></div>;
}

function Incident({ glitch, editable, edit }: { glitch: GlitchRecord; editable: boolean; edit: () => void }) { return <section><SectionTitle title="Incident" action={editable ? <button onClick={edit} className="text-xs font-semibold text-[var(--color-kahel-700)]">Edit</button> : null} /><p className="whitespace-pre-wrap text-sm leading-6 text-[var(--color-text-secondary)]">{glitch.description}</p>{glitch.operationsBlocked ? <div className="mt-3 inline-flex items-center gap-2 rounded-control bg-[var(--color-danger-bg)] px-3 py-2 text-xs font-semibold text-[var(--color-danger-text)]"><AlertTriangle className="h-4 w-4" /> Operations currently blocked</div> : null}<dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><Info label="Location / system" value={glitch.locationOrSystem ?? "Not specified"} /><Info label="Observed" value={formatGlitchDate(glitch.observedAt)} /><Info label="Reported by" value={glitch.reportedBy} /><Info label="Assigned to" value={glitch.assignedTo ?? "Unassigned"} /><Info label="Client" value={glitch.client ?? "Not linked"} /><Info label="Booking" value={glitch.booking ?? "Not linked"} /><Info label="Project" value={glitch.project ?? "Not linked"} /><Info label="Follow-up task" value={glitch.linkedTask ?? "Not linked"} /></dl>{glitch.workaround ? <div className="mt-4"><h4 className="text-xs font-semibold uppercase tracking-[0.05em] text-[var(--color-text-muted)]">Temporary workaround</h4><p className="mt-1 whitespace-pre-wrap text-sm text-[var(--color-text-secondary)]">{glitch.workaround}</p></div> : null}</section>; }
function EditForm({ glitch, admin, cancel, submit, busy }: { glitch: GlitchRecord; admin: boolean; cancel: () => void; submit: (body: Record<string, unknown>) => Promise<void>; busy: boolean }) { return <form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit({ title: form.get("title"), description: form.get("description"), category: form.get("category") ?? glitch.category, severity: form.get("severity") ?? glitch.severity, locationOrSystem: form.get("locationOrSystem"), workaround: form.get("workaround"), operationsBlocked: form.get("operationsBlocked") === "on" }); }}><SectionTitle title="Edit incident" /><div className="grid gap-3"><Field label="Issue title"><input name="title" required defaultValue={glitch.title} className="glitch-input" /></Field><Field label="Description"><textarea name="description" required rows={4} defaultValue={glitch.description} className="glitch-input h-auto py-2.5" /></Field>{admin ? <div className="grid gap-3 sm:grid-cols-2"><SelectField label="Category" name="category" options={GLITCH_CATEGORIES} defaultValue={glitch.category} /><SelectField label="Severity" name="severity" options={GLITCH_SEVERITIES} defaultValue={glitch.severity} /></div> : null}<Field label="Location or affected system"><input name="locationOrSystem" defaultValue={glitch.locationOrSystem ?? ""} className="glitch-input" /></Field><Field label="Workaround"><textarea name="workaround" defaultValue={glitch.workaround ?? ""} rows={2} className="glitch-input h-auto py-2.5" /></Field><label className="flex items-center gap-2 text-sm font-semibold"><input name="operationsBlocked" type="checkbox" defaultChecked={glitch.operationsBlocked} className="accent-[#FF5300]" /> Operations currently blocked</label><div className="flex justify-end gap-2"><button type="button" onClick={cancel} className="h-10 px-3 text-sm font-semibold">Cancel</button><button disabled={busy} className="h-10 rounded-control bg-[#FF5300] px-4 text-sm font-semibold text-white disabled:opacity-50">Save changes</button></div></div></form>; }
function UpdateForm({ submit, busy }: { submit: (message: string) => Promise<boolean>; busy: boolean }) { const [message, setMessage] = useState(""); return <section><SectionTitle title="Internal update" /><form onSubmit={async (event) => { event.preventDefault(); if (await submit(message)) setMessage(""); }} className="flex gap-2"><input value={message} onChange={(event) => setMessage(event.target.value)} required minLength={2} placeholder="Add context, findings, or progress…" className="glitch-input" /><button disabled={busy} className="h-11 rounded-control bg-[#FF5300] px-4 text-sm font-semibold text-white disabled:opacity-50">Add</button></form></section>; }
function ResolveForm({ submit, busy }: { submit: (summary: string, at: string) => Promise<boolean>; busy: boolean }) { const [summary, setSummary] = useState(""); return <section><SectionTitle title="Resolve glitch" /><form onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); void submit(summary, String(form.get("resolvedAt"))); }} className="grid gap-3"><textarea value={summary} onChange={(event) => setSummary(event.target.value)} required minLength={3} rows={3} placeholder="Resolution summary" className="glitch-input h-auto py-2.5" /><Field label="Resolution date and time"><input name="resolvedAt" type="datetime-local" required defaultValue={localDateTime()} className="glitch-input" /></Field><p className="text-xs text-[var(--color-text-muted)]">Resolved by the signed-in user.</p><button disabled={busy} className="h-11 w-fit rounded-control bg-[#FF5300] px-4 text-sm font-semibold text-white disabled:opacity-50">Mark as resolved</button></form></section>; }
function ReopenForm({ submit, busy }: { submit: (reason: string) => Promise<boolean>; busy: boolean }) { const [reason, setReason] = useState(""); return <section><SectionTitle title="Reopen" /><form onSubmit={(event) => { event.preventDefault(); void submit(reason); }} className="flex gap-2"><input value={reason} onChange={(event) => setReason(event.target.value)} required minLength={3} placeholder="Reason for reopening" className="glitch-input" /><button disabled={busy} className="h-11 rounded-control border border-[var(--color-border)] px-4 text-sm font-semibold" aria-label="Reopen glitch"><RotateCcw className="h-4 w-4" /></button></form></section>; }
function TaskActions({ workspace, glitch, mutate, busy }: { workspace: GlitchesWorkspace; glitch: GlitchRecord; mutate: (action: string, body?: Record<string, unknown>) => Promise<boolean>; busy: boolean }) { const [taskId, setTaskId] = useState(glitch.linkedTaskId ?? ""); return <div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><select value={taskId} onChange={(event) => setTaskId(event.target.value)} className="glitch-input"><option value="">Choose follow-up task</option>{workspace.tasks.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select><button disabled={busy || !taskId} onClick={() => void mutate("link_task", { taskId })} className="inline-flex h-11 items-center justify-center gap-2 rounded-control border border-[var(--color-border)] px-3 text-sm font-semibold disabled:opacity-40"><Link2 className="h-4 w-4" /> Link</button><button disabled={busy} onClick={() => void mutate("create_task", { description: glitch.description })} className="h-11 rounded-control border border-[var(--color-border)] px-3 text-sm font-semibold">Create task</button></div>; }
function DialogFrame({ title, subtitle, close, locked, children }: { title: string; subtitle: string; close: () => void; locked: boolean; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-labelledby="glitch-dialog-title" onMouseDown={(event) => { if (event.target === event.currentTarget && !locked) close(); }}><div className="max-h-[calc(100dvh-1rem)] w-full overflow-y-auto rounded-t-modal border border-[var(--color-border)] bg-[var(--color-surface)] shadow-[var(--shadow-dialog)] sm:max-w-2xl sm:rounded-modal"><header className="flex items-start gap-4 border-b border-[var(--color-border)] p-5"><div><h2 id="glitch-dialog-title" className="font-display text-xl font-semibold">{title}</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">{subtitle}</p></div><button onClick={close} disabled={locked} className="ml-auto grid min-h-11 min-w-11 place-items-center rounded-control hover:bg-[var(--color-surface-muted)]" aria-label="Close dialog"><X className="h-4 w-4" /></button></header>{children}</div></div>; }
function DialogActions({ close, submitting, label }: { close: () => void; submitting: boolean; label: string }) { return <div className="flex justify-end gap-2 border-t border-[var(--color-border)] p-4"><button type="button" onClick={close} disabled={submitting} className="h-11 px-4 text-sm font-semibold">Cancel</button><button disabled={submitting} className="h-11 rounded-control bg-[#FF5300] px-4 text-sm font-semibold text-white disabled:opacity-50">{submitting ? "Saving…" : label}</button></div>; }
function Field({ label, className = "", children }: { label: string; className?: string; children: React.ReactNode }) { return <label className={`block text-sm font-semibold ${className}`}><span className="mb-1.5 block">{label}</span>{children}</label>; }
function SelectField({ label, name, options, defaultValue }: { label: string; name: string; options: readonly string[]; defaultValue: string }) { return <Field label={label}><select name={name} defaultValue={defaultValue} required className="glitch-input">{options.map((option) => <option key={option}>{option}</option>)}</select></Field>; }
function OptionField({ label, name, options }: { label: string; name: string; options: GlitchOption[] }) { return <Field label={label}><select name={name} className="glitch-input"><option value="">None</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></Field>; }
function ActionSelect({ label, value, options, change, disabled }: { label: string; value: string; options: GlitchOption[]; change: (value: string) => void; disabled: boolean }) { return <Field label={label}><select value={value} onChange={(event) => change(event.target.value)} disabled={disabled} className="glitch-input"><option value="">Unassigned</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></Field>; }
function SectionTitle({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="mb-3 flex items-center justify-between border-b border-[var(--color-border)] pb-2"><h3 className="font-display text-base font-semibold">{title}</h3>{action}</div>; }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold text-[var(--color-text-muted)]">{label}</dt><dd className="mt-1 text-[var(--color-text-primary)]">{value}</dd></div>; }
function localDateTime() { const date = new Date(); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); }
async function loadAttachments(glitchId: string): Promise<AttachmentDownload[]> { const response = await fetch(`/api/glitches/${glitchId}/attachments`); return response.ok ? await response.json() as AttachmentDownload[] : []; }
