drop table if exists public.staff_notifications cascade;
drop table if exists public.approval_audit_log cascade;
drop table if exists public.approval_liquidation_items cascade;
drop table if exists public.approval_financial_events cascade;
drop table if exists public.approval_attachments cascade;
drop table if exists public.approval_comments cascade;
drop table if exists public.approval_steps cascade;
drop table if exists public.approval_requests cascade;
drop table if exists public.approval_workflow_rules cascade;
drop table if exists public.approval_reference_counters cascade;
drop function if exists public.approval_enqueue_due_notifications();
drop function if exists public.approval_can_view(uuid);
drop function if exists public.approval_record_financial_event(uuid, uuid, text, integer, text, text, timestamptz, text);
drop function if exists public.approval_withdraw_request(uuid, uuid, text);
drop function if exists public.approval_archive_request(uuid, uuid, text);
drop function if exists public.approval_update_workflow_rule(uuid, uuid, integer, integer, boolean, integer, boolean);
drop function if exists public.approval_decide_request(uuid, uuid, text, text);
drop function if exists public.approval_add_comment(uuid, uuid, text, text);
drop function if exists public.approval_reassign_step(uuid, uuid, uuid, text, boolean);
drop function if exists public.approval_bulk_approve(uuid[], uuid, text);
drop function if exists public.approval_submit_request(uuid, uuid, text);
drop function if exists public.approval_update_request(uuid, uuid, text, text, text, jsonb, date, integer, text, boolean);
drop function if exists public.approval_create_request(uuid, uuid, text, text, text, text, text, jsonb, boolean, date, integer, text, uuid, uuid, uuid, uuid, uuid, text, text);
drop function if exists public.approval_select_rule(text, integer);
drop function if exists public.approval_refresh_cash_advance_liquidation(uuid);
drop function if exists public.approval_next_reference();
drop function if exists public.prevent_approval_immutable_mutation();
drop function if exists public.audit_approval_attachment();
